# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

GITHUB_COMMENT_REPORTER: false

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:
#   - RUST

DISABLE:
  - SPELL

DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GRYPE
  - REPOSITORY_KICS

# PRE_COMMANDS:
#   - command: apk add --no-cache zlib-dev zlib-static openssl-dev libffi-dev

SHOW_ELAPSED_TIME: true

FILTER_REGEX_EXCLUDE: ^(examples/docs|\.github/workflows)
