[workspace]
changelog_update = false
git_release_enable = false
git_tag_enable = false

[[package]]
name = "usage-cli"
changelog_update = true
changelog_path = "./CHANGELOG.md"
changelog_include = ["usage-lib"]
git_tag_name = "v${version}"
git_tag_enable = true
git_release_enable = true

# [[package]]
# name = "usage-lib"
