[workspace]
changelog_update = false
dependencies_update = true
git_release_enable = false
git_tag_enable = false
pr_labels = ["release"]

[[package]]
name = "usage-cli"
changelog_include = ["usage-lib"]
changelog_path = "./CHANGELOG.md"
changelog_update = true
git_release_enable = true
git_tag_enable = true
git_tag_name = "v${version}"
