name: Set up mbx
description: Set up mbx with the GitHub Actions cache backend

runs:
  using: composite
  steps:
    - uses: jdx/mr-boxington-action@203ebddb3bdb1b3832473207d0a837b23b660563
      with:
        version: 1.1.0
        backend: github
        cache-generation: v2
