//! mise declared in cobra.
//!
//! A library package rather than a program: the benchmark that times it links all
//! four frameworks into one binary and sweeps them in the same process, the way
//! `benches/gate/src/bin/time-sweep.rs` does for the Rust four.
//!
//! The tree is built inside `Resolve` on purpose. That is what cobra does on every
//! process start — a `&cobra.Command` per subcommand, each with its own flag set — and
//! it is the cost the comparison is about. Hoisting it out would measure a parser
//! against a program that had already paid for its model.

use super::*;

pub fn render(spec: &Spec, spec_path: &Path, skipped: &mut Skipped) -> String {
    let mut out = String::new();
    let bin = &spec.bin;

    let _ = writeln!(
        out,
        "// Code generated by `xtask gen-shadow {} <out> cobra`. DO NOT EDIT.\n\
         //\n\
         // {bin} declared in cobra, from the same spec the usage tables are generated\n\
         // from, so that the rows of `go/README.md`'s tables describe the same CLI.\n\
         // Regenerate with `mise run gen-shadow` rather than editing: a hand-edit here is a\n\
         // difference no reviewer can see, in a program whose whole job is to be comparable.\n\
         package {bin}cobra\n\n\
         import \"github.com/spf13/cobra\"\n",
        spec_path.display(),
    );

    let mut body = String::new();
    // A counter rather than a path of indices: `root1` and `root1`'s own eleventh child both
    // spell themselves `root11`, and Go says so with "no new variables on left side of :=".
    let mut next = 0usize;
    emit_command(&mut body, &spec.cmd, "root", bin, &mut next, skipped);

    let _ = writeln!(
        out,
        "// build declares the whole CLI, as a cobra program's `init` or `main` would.\n\
         func build() *cobra.Command {{\n\
         {body}\treturn root\n\
         }}\n"
    );

    // Find and ParseFlags rather than Execute: the comparison is about resolving a command
    // line, and Execute would run the command as well. This is the same work the usage side
    // does — reach a command, bind its flags — and no more.
    let _ = writeln!(
        out,
        "// Resolve builds cobra's model of the CLI and resolves argv against it, reporting\n\
         // whether a subcommand was reached. Both halves are the measurement: cobra has no\n\
         // way to answer a command line without first constructing the tree.\n\
         func Resolve(argv []string) bool {{\n\
         \troot := build()\n\
         \tcmd, flags, err := root.Find(argv)\n\
         \tif err == nil {{\n\
         \t\terr = cmd.ParseFlags(flags)\n\
         \t}}\n\
         \treturn err == nil && cmd != root\n\
         }}"
    );
    out
}

/// One command and everything under it, as statements building `var`.
fn emit_command(
    out: &mut String,
    cmd: &SpecCommand,
    var: &str,
    use_name: &str,
    next: &mut usize,
    skipped: &mut Skipped,
) {
    let mut fields = vec![format!("Use: {}", go_string(use_name))];
    if let Some(help) = cmd.help.as_deref().or(cmd.help_long.as_deref()) {
        fields.push(format!("Short: {}", go_string(help)));
    }
    if let Some(long) = &cmd.help_long {
        fields.push(format!("Long: {}", go_string(long)));
    }
    // Both lists: cobra has one `Aliases`, and hiding an alias is not something it can say.
    let aliases: Vec<String> = cmd
        .aliases
        .iter()
        .chain(cmd.hidden_aliases.iter())
        .cloned()
        .collect();
    if !aliases.is_empty() {
        fields.push(format!("Aliases: {}", string_slice(&aliases)));
    }
    if !cmd.hidden_aliases.is_empty() {
        skipped.note("hidden aliases (cobra hides a command, not an alias)");
    }
    if cmd.hide {
        fields.push("Hidden: true".to_string());
    }
    // A leaf needs a Run for cobra to treat it as runnable; without one it prints help and
    // `Find` still resolves it, which is all this program asks of it.
    fields.push("Run: func(*cobra.Command, []string) {}".to_string());

    let _ = writeln!(out, "\t{var} := &cobra.Command{{{}}}", fields.join(", "));

    for flag in &cmd.flags {
        emit_flag(out, flag, var, skipped);
    }
    for arg in &cmd.args {
        note_arg(arg, skipped);
    }

    for (name, sub) in subcommands(cmd) {
        *next += 1;
        let child = format!("cmd{next}");
        emit_command(out, sub, &child, name, next, skipped);
        let _ = writeln!(out, "\t{var}.AddCommand({child})");
    }

    // One per mount, wherever it is. mise's are on `run` and `tasks` rather than at the root,
    // so a check that only looked there dropped them without saying so — in the one report
    // this whole shadow relies on for honesty. Counted per entry because a command may graft
    // in more than one, and the report is a count.
    for _ in &cmd.mounts {
        skipped.note("mounts (another spec grafted in at run time)");
    }
}

/// One flag, registered on the command that declares it.
fn emit_flag(out: &mut String, flag: &SpecFlag, var: &str, skipped: &mut Skipped) {
    let Some(long) = flag.long.first() else {
        // cobra has no vocabulary for a short-only flag: `Flags().BoolP` takes a name and a
        // shorthand, and the name is the long form.
        skipped.note("short-only flags");
        return;
    };
    let short = flag
        .short
        .first()
        .map(|c| c.to_string())
        .unwrap_or_default();
    let help = flag
        .help
        .as_deref()
        .or(flag.help_first_line.as_deref())
        .unwrap_or_default();

    // Which flag set: a global belongs to the command's persistent set, which is how cobra
    // spells "in scope for everything below".
    let set = if flag.global {
        "PersistentFlags"
    } else {
        "Flags"
    };

    let (method, default) = match (&flag.arg, flag.count, flag.var) {
        (None, true, _) => ("Count", String::new()),
        (None, false, _) => ("Bool", "false".to_string()),
        (Some(_), _, true) => ("StringArray", "nil".to_string()),
        (Some(_), _, false) => (
            "String",
            go_string(flag.default.first().map(String::as_str).unwrap_or("")),
        ),
    };

    let with_short = if short.is_empty() { "" } else { "P" };
    let mut args = vec![go_string(long)];
    if !short.is_empty() {
        args.push(go_string(&short));
    }
    if !default.is_empty() {
        args.push(default);
    }
    args.push(go_string(help));

    let _ = writeln!(
        out,
        "\t{var}.{set}().{method}{with_short}({})",
        args.join(", ")
    );

    if flag.hide {
        let _ = writeln!(out, "\t_ = {var}.{set}().MarkHidden({})", go_string(long));
    }
    if flag.negate.is_some() {
        skipped.note("negations (`--no-x` is a flag of its own in cobra)");
    }
    if flag.long.len() > 1 {
        skipped.note("second and later long forms");
    }
    if flag.short.len() > 1 {
        skipped.note("second and later short forms");
    }
    if flag.required {
        // Expressible, and left out on purpose: `MarkFlagRequired` is enforced by `Execute`,
        // which this program does not call, so declaring it would cost nothing and be
        // measured as though it did.
        skipped.note("required (enforced by Execute, which is not what is measured)");
    }
}

/// Positionals, which cobra does not declare.
fn note_arg(arg: &SpecArg, skipped: &mut Skipped) {
    let _ = arg;
    skipped.note("positional arguments (cobra validates a count, not a name)");
}
