//! mise declared in kong.
//!
//! kong is the framework that gives Go the ergonomics people actually want — the CLI
//! is a struct, and the tags on it say what the flags are — and this is what that
//! costs: the grammar is discovered by walking the struct with reflection on every
//! process start, because reflection is the only way to read tags without a build
//! step.
//!
//! So a struct per command, and a tag per flag, which is what an author would write
//! by hand. `kong.New` is called inside `Resolve` for the same reason cobra's tree is
//! built there: it is not a step a CLI gets to skip.

use super::*;

use std::collections::{HashMap, HashSet};

pub fn render(spec: &Spec, spec_path: &Path, skipped: &mut Skipped) -> String {
    let mut out = String::new();
    let bin = &spec.bin;

    let _ = writeln!(
        out,
        "// Code generated by `xtask gen-shadow {} <out> kong`. DO NOT EDIT.\n\
         //\n\
         // {bin} declared in kong, from the same spec the usage tables are generated from,\n\
         // so that the rows of `go/README.md`'s tables describe the same CLI. Regenerate\n\
         // with `mise run gen-shadow` rather than editing.\n\
         //\n\
         // One struct per command and one tag per flag, as an author would write them.\n\
         // `kong.New` walks all of it with reflection inside `Resolve`, because that is\n\
         // what a kong program does on every process start.\n\
         package {bin}kong\n\n\
         import (\n\
         \t\"io\"\n\n\
         \t\"github.com/alecthomas/kong\"\n\
         )\n",
        spec_path.display(),
    );

    let mut types = Types::default();
    let root = types.emit(&spec.cmd, "Cli", &Inherited::default(), skipped);
    debug_assert_eq!(root, "Cli");
    for decl in &types.decls {
        out.push_str(decl);
        out.push('\n');
    }

    // Writers and Exit rather than the defaults: kong prints to stderr and calls
    // os.Exit when it is asked for help, and a harness that let it would measure the
    // page being written or not finish at all.
    let _ = writeln!(
        out,
        "// Resolve builds kong's model of the CLI by reflecting over the structs above and\n\
         // parses argv against it, reporting whether a subcommand was reached.\n\
         //\n\
         // Both halves are the measurement: kong has no way to answer a command line\n\
         // without first walking the whole grammar.\n\
         func Resolve(argv []string) bool {{\n\
         \tvar target Cli\n\
         \tparser, err := kong.New(&target, kong.Name({}),\n\
         \t\tkong.Exit(func(int) {{}}), kong.Writers(io.Discard, io.Discard))\n\
         \tif err != nil {{\n\
         \t\treturn false\n\
         \t}}\n\
         \tctx, err := parser.Parse(argv)\n\
         \tif err != nil {{\n\
         \t\treturn false\n\
         \t}}\n\
         \treturn ctx.Selected() != nil\n\
         }}",
        go_string(bin),
    );
    out
}

/// The struct declarations, and the names already taken by one.
#[derive(Default)]
struct Types {
    decls: Vec<String>,
    taken: HashMap<String, usize>,
}

impl Types {
    /// Declare a type for `cmd` and everything under it, returning its name.
    fn emit(
        &mut self,
        cmd: &SpecCommand,
        suggested: &str,
        inherited: &Inherited,
        skipped: &mut Skipped,
    ) -> String {
        let name = self.reserve(suggested);
        // Reserved before the children are walked, so a child cannot take this name, and
        // the declaration is pushed afterwards: the body needs the children's names.
        let slot = self.decls.len();
        self.decls.push(String::new());

        let has_subcommands = subcommands(cmd).next().is_some();

        let mut scope = inherited.clone();
        let mut fields = Fields::default();
        for flag in &cmd.flags {
            if let Some(field) = flag_field(flag, has_subcommands, &mut scope, &mut fields, skipped)
            {
                fields.push(field);
            }
        }
        // kong wants the optional positionals last and refuses the grammar outright
        // otherwise. A spec is free to say `<a> [b] <c>`, so once one is optional the rest
        // are declared that way too, which is a looser CLI than the spec describes.
        let mut after_optional = false;
        // And a variadic one has to be the last of them: kong reads it as taking
        // everything that is left, so nothing can follow it.
        let mut after_variadic = false;
        for arg in &cmd.args {
            if has_subcommands {
                // kong refuses the mix outright — "can't mix positional arguments and
                // branching arguments" — so on a command that has subcommands the
                // positionals are what has to go. mise's root is one of these: `mise
                // <TASK>` and `mise use …` cannot both be said here.
                skipped.note("positionals on a command that also has subcommands");
                continue;
            }
            if after_variadic {
                skipped.note("positionals after a variadic one (kong's takes what is left)");
                continue;
            }
            if let Some(field) = arg_field(arg, after_optional, &mut fields, skipped) {
                fields.push(field);
            }
            after_optional |= !arg.required;
            after_variadic |= arg.var;
        }

        for (child_name, sub) in subcommands(cmd) {
            let suggested = format!("{}{}Cmd", trim_cmd(&name), pascal(child_name));
            let ty = self.emit(sub, &suggested, &scope, skipped);
            let ident = fields.ident(&pascal(child_name));
            let mut tag = vec![format!("cmd:\"\" name:{}", tag_value(child_name))];
            if let Some(help) = sub.help.as_deref().or(sub.help_long.as_deref()) {
                tag.push(format!("help:{}", tag_value(help)));
            }
            // Both lists, as the other shadows do: kong has one `aliases` and no way to
            // say that one of them is hidden.
            let aliases: Vec<String> = sub
                .aliases
                .iter()
                .chain(sub.hidden_aliases.iter())
                .cloned()
                .collect();
            if !aliases.is_empty() {
                tag.push(format!("aliases:{}", tag_value(&aliases.join(","))));
            }
            if !sub.hidden_aliases.is_empty() {
                skipped.note("hidden aliases (kong hides a command, not an alias)");
            }
            if sub.hide {
                tag.push("hidden:\"\"".to_string());
            }
            fields.push(format!("\t{ident} {ty} {}\n", go_string(&tag.join(" "))));
        }

        for _ in &cmd.mounts {
            skipped.note("mounts (another spec grafted in at run time)");
        }

        // The root's `full_cmd` is empty, and a doc comment reading "Cli is ``" says
        // less than nothing.
        let path = cmd.full_cmd.join(" ");
        let mut decl = String::new();
        match (
            path.is_empty(),
            cmd.help.as_deref().or(cmd.help_long.as_deref()),
        ) {
            (true, _) => {
                let _ = writeln!(decl, "// {name} is the root command.");
            }
            (false, Some(help)) => {
                // One line: a doc comment is `//` per line, and mise's help runs to
                // paragraphs.
                let line = help.lines().next().unwrap_or_default();
                let _ = writeln!(decl, "// {name} is `{path}`: {line}");
            }
            (false, None) => {
                let _ = writeln!(decl, "// {name} is `{path}`.");
            }
        }
        let _ = write!(decl, "type {name} struct {{\n{}}}\n", fields.body);
        self.decls[slot] = decl;
        name
    }

    /// A type name nothing else has taken.
    ///
    /// Two commands of the same name under different parents produce the same suggestion
    /// — mise has thirteen `status` commands — and Go says so at compile time rather than
    /// quietly using one of them.
    fn reserve(&mut self, suggested: &str) -> String {
        let n = self.taken.entry(suggested.to_string()).or_insert(0);
        *n += 1;
        if *n == 1 {
            suggested.to_string()
        } else {
            format!("{suggested}{n}")
        }
    }
}

/// The fields of one struct, and the names already taken by one.
#[derive(Default)]
struct Fields {
    body: String,
    taken: HashMap<String, usize>,
}

impl Fields {
    fn push(&mut self, field: String) {
        self.body.push_str(&field);
    }

    /// A field name nothing else in this struct has taken. `--dry-run` and `--dryRun`
    /// both want to be `DryRun`, and a struct with the field twice does not compile.
    fn ident(&mut self, suggested: &str) -> String {
        let n = self.taken.entry(suggested.to_string()).or_insert(0);
        *n += 1;
        if *n == 1 {
            suggested.to_string()
        } else {
            format!("{suggested}{n}")
        }
    }
}

/// The flag names an ancestor has already declared.
///
/// kong has no shadowing: a flag on a parent is in scope for every child, and a child
/// that declares the same name is a duplicate that `kong.New` refuses outright. mise
/// redeclares `--quiet` and friends on subcommands, where a spec means "this one wins
/// here", so those are dropped rather than declared twice.
#[derive(Clone, Default)]
struct Inherited {
    longs: HashSet<String>,
    shorts: HashSet<char>,
}

/// One flag, as a struct field with the tags a kong author would write.
fn flag_field(
    flag: &SpecFlag,
    has_subcommands: bool,
    scope: &mut Inherited,
    fields: &mut Fields,
    skipped: &mut Skipped,
) -> Option<String> {
    let Some(long) = flag.long.first() else {
        // Every kong flag is a struct field, and a field has a name, so the long form is
        // not optional the way it is in a spec.
        skipped.note("short-only flags");
        return None;
    };
    if long == "help" {
        // kong declares `--help` itself and rejects the duplicate at `New` time, which
        // would fail every parse rather than measuring one.
        skipped.note("`--help` (kong declares its own)");
        return None;
    }
    if !scope.longs.insert(long.clone()) {
        skipped.note("flags a parent already declares (kong has no shadowing)");
        return None;
    }

    let mut tag = vec![format!("name:{}", tag_value(long))];
    // The short form goes only to the first flag that asks for it, for the same reason:
    // an inherited `-q` is still `-q` inside a subcommand.
    if let Some(short) = flag.short.first().filter(|c| scope.shorts.insert(**c)) {
        tag.push(format!("short:{}", tag_value(&short.to_string())));
    } else if !flag.short.is_empty() {
        skipped.note("short forms a parent already declares (kong has no shadowing)");
    }
    if flag.short.len() > 1 {
        skipped.note("second and later short forms");
    }
    if flag.long.len() > 1 {
        tag.push(format!("aliases:{}", tag_value(&flag.long[1..].join(","))));
    }
    if let Some(help) = flag.help.as_deref().or(flag.help_first_line.as_deref()) {
        tag.push(format!("help:{}", tag_value(help)));
    }
    if flag.hide {
        tag.push("hidden:\"\"".to_string());
    }
    if flag.required {
        tag.push("required:\"\"".to_string());
    }
    if let Some(env) = flag.env.as_deref() {
        tag.push(format!("env:{}", tag_value(env)));
    }
    if flag.negate.is_some() {
        // kong's `negatable` derives the negated spelling from the flag's own name, and a
        // spec says it outright — `--no-config` for `--config` is not `--no-config`'s
        // business to guess.
        skipped.note("negations (kong derives the spelling rather than taking it)");
    }
    if !flag.global && has_subcommands {
        // A kong flag declared on a node is in scope for every node below it, which is
        // what a spec calls global. There is no way to say "here and no deeper" — so this
        // is only a difference on a command that has subcommands to leak into.
        skipped.note("command-local flags on a branch (kong's reach everything below)");
    }

    let ty = match (&flag.arg, flag.count, flag.var) {
        (None, true, _) => {
            tag.push("type:\"counter\"".to_string());
            "int"
        }
        (None, false, _) => "bool",
        (Some(_), _, true) => "[]string",
        (Some(_), _, false) => {
            if let Some(default) = flag.default.first() {
                tag.push(format!("default:{}", tag_value(default)));
            }
            "string"
        }
    };
    if flag.arg.as_ref().is_some_and(|a| a.choices.is_some()) {
        // `enum` is expressible and left out: kong requires an enum flag to be required
        // or to have a default that is one of the values, and a spec's choices carry
        // neither, so declaring them would change which command lines parse.
        skipped.note("choices (kong's enum needs a default or required)");
    }

    let ident = fields.ident(&pascal(long));
    Some(format!("\t{ident} {ty} {}\n", go_string(&tag.join(" "))))
}

/// One positional, as a struct field with `arg:""`.
fn arg_field(
    arg: &SpecArg,
    after_optional: bool,
    fields: &mut Fields,
    skipped: &mut Skipped,
) -> Option<String> {
    let mut tag = vec![format!("arg:\"\" name:{}", tag_value(&arg.name))];
    if !arg.required {
        tag.push("optional:\"\"".to_string());
    } else if after_optional {
        skipped.note("required positionals after an optional one (kong wants those last)");
        tag.push("optional:\"\"".to_string());
    }
    if let Some(help) = arg.help.as_deref().or(arg.help_first_line.as_deref()) {
        tag.push(format!("help:{}", tag_value(help)));
    }
    if arg.choices.is_some() {
        skipped.note("choices (kong's enum needs a default or required)");
    }
    let ty = if arg.var { "[]string" } else { "string" };
    let ident = fields.ident(&pascal(&arg.name));
    Some(format!("\t{ident} {ty} {}\n", go_string(&tag.join(" "))))
}

/// `"use"` as a struct-tag value: quoted, and quoted again by the caller's `go_string`.
///
/// A struct tag is a string whose values are themselves quoted strings, so a help line
/// with a `"` in it has to survive two layers. `reflect.StructTag` reads the inner one
/// and Go's lexer the outer.
fn tag_value(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            // A tag value is one line by the time reflect reads it: kong prints help as
            // it finds it, and a newline inside a tag is not something `StructTag` gives
            // back intact.
            '\n' | '\r' | '\t' => out.push(' '),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// `tool-alias` as `ToolAlias`.
fn pascal(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut upper = true;
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            if upper {
                out.extend(c.to_uppercase());
            } else {
                out.push(c);
            }
            upper = false;
        } else {
            upper = true;
        }
    }
    if out.is_empty() || out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, 'X');
    }
    out
}

/// `ToolAliasCmd` as `ToolAlias`, so a grandchild reads `ToolAliasGetCmd` rather than
/// `ToolAliasCmdGetCmd`.
fn trim_cmd(name: &str) -> &str {
    if name == "Cli" {
        return "";
    }
    name.strip_suffix("Cmd").unwrap_or(name)
}
