//! mise declared in urfave/cli v3.
//!
//! Where cobra hands out a `Find` that resolves a command line without running it,
//! urfave has one entry point: `Run` sets the tree up, parses, and calls the action
//! it arrived at. So the shadow's actions are empty and `Resolve` reports which one
//! fired. That is a hair more than the other three rows do — a dispatch through one
//! empty closure — and it is what an urfave program cannot avoid doing.

use super::*;

pub fn render(spec: &Spec, spec_path: &Path, skipped: &mut Skipped) -> String {
    let mut out = String::new();
    let bin = &spec.bin;

    let _ = writeln!(
        out,
        "// Code generated by `xtask gen-shadow {} <out> urfave`. DO NOT EDIT.\n\
         //\n\
         // {bin} declared in urfave/cli v3, from the same spec the usage tables are\n\
         // generated from, so that the rows of `go/README.md`'s tables describe the same\n\
         // CLI. Regenerate with `mise run gen-shadow` rather than editing.\n\
         //\n\
         // The tree is built inside `Resolve` on purpose: that is what an urfave program\n\
         // does on every process start, and it is the cost the comparison is about.\n\
         package {bin}urfave\n\n\
         import (\n\
         \t\"context\"\n\
         \t\"io\"\n\n\
         \t\"github.com/urfave/cli/v3\"\n\
         )\n",
        spec_path.display(),
    );

    let has_subcommands = subcommands(&spec.cmd).next().is_some();

    let mut body = String::new();
    let mut next = 0usize;
    let root = emit_command(&mut body, &spec.cmd, bin, true, &mut next, skipped);

    // Declared once and shared, rather than a closure per command: a func value that
    // captures nothing is laid out by the compiler, and one that captures `hit` would
    // otherwise be allocated 211 times and charged to urfave's model-building.
    let mut helpers =
        String::from("\tnoop := func(context.Context, *cli.Command) error { return nil }\n");
    if has_subcommands {
        helpers.push_str(
            "\treached := func(context.Context, *cli.Command) error { *hit = true; return nil }\n",
        );
    }

    let _ = writeln!(
        out,
        "// build declares the whole CLI, as an urfave program's `main` would.\n\
         //\n\
         // `hit` is set by the action of whichever subcommand the parse arrives at, which is\n\
         // how this shadow answers the same question the others do — was a subcommand\n\
         // reached — without an action that does any work.\n\
         func build(hit *bool) *cli.Command {{\n\
         {helpers}{body}\treturn {root}\n\
         }}\n"
    );

    let _ = writeln!(
        out,
        "// Resolve builds urfave's model of the CLI and runs argv against it, reporting\n\
         // whether a subcommand was reached.\n\
         //\n\
         // argv arrives without the program name, the way the other shadows take it, and\n\
         // `Run` wants it with one — hence the copy, which is a few dozen nanoseconds\n\
         // against a parse three orders of magnitude larger.\n\
         func Resolve(argv []string) bool {{\n\
         \thit := false\n\
         \troot := build(&hit)\n\
         \targs := make([]string, 0, len(argv)+1)\n\
         \targs = append(args, {})\n\
         \targs = append(args, argv...)\n\
         \tif err := root.Run(context.Background(), args); err != nil {{\n\
         \t\treturn false\n\
         \t}}\n\
         \treturn hit\n\
         }}",
        go_string(bin),
    );
    out
}

/// One command and everything under it. Children are declared first, so the parent can
/// name them in its `Commands` list; the returned name is this command's variable.
fn emit_command(
    out: &mut String,
    cmd: &SpecCommand,
    name: &str,
    is_root: bool,
    next: &mut usize,
    skipped: &mut Skipped,
) -> String {
    let children: Vec<String> = subcommands(cmd)
        .map(|(child_name, sub)| emit_command(out, sub, child_name, false, next, skipped))
        .collect();

    let var = if is_root {
        "root".to_string()
    } else {
        *next += 1;
        format!("cmd{next}")
    };

    let mut fields = vec![format!("Name: {}", go_string(name))];
    if let Some(help) = cmd.help.as_deref().or(cmd.help_long.as_deref()) {
        fields.push(format!("Usage: {}", go_string(help)));
    }
    if let Some(long) = &cmd.help_long {
        fields.push(format!("Description: {}", go_string(long)));
    }
    // Both lists: urfave has one `Aliases`, and hiding an alias is not something it can say.
    let aliases: Vec<String> = cmd
        .aliases
        .iter()
        .chain(cmd.hidden_aliases.iter())
        .cloned()
        .collect();
    if !aliases.is_empty() {
        fields.push(format!("Aliases: {}", string_slice(&aliases)));
    }
    if !cmd.hidden_aliases.is_empty() {
        skipped.note("hidden aliases (urfave hides a command, not an alias)");
    }
    if cmd.hide {
        fields.push("Hidden: true".to_string());
    }
    if is_root {
        // A parse that fails must not print a help page down the harness's stdout, and a
        // program that printed one would be measured writing it.
        fields.push("Writer: io.Discard".to_string());
        fields.push("ErrWriter: io.Discard".to_string());
    }
    fields.push(format!(
        "Action: {}",
        if is_root { "noop" } else { "reached" }
    ));

    let flags: Vec<String> = cmd
        .flags
        .iter()
        .filter_map(|flag| emit_flag(flag, skipped))
        .collect();
    if !flags.is_empty() {
        fields.push(format!("Flags: []cli.Flag{{{}}}", flags.join(", ")));
    }

    let args: Vec<String> = cmd.args.iter().map(|arg| emit_arg(arg, skipped)).collect();
    if !args.is_empty() {
        fields.push(format!("Arguments: []cli.Argument{{{}}}", args.join(", ")));
    }

    if !children.is_empty() {
        fields.push(format!(
            "Commands: []*cli.Command{{{}}}",
            children.join(", ")
        ));
    }

    for _ in &cmd.mounts {
        skipped.note("mounts (another spec grafted in at run time)");
    }

    let _ = writeln!(out, "\t{var} := &cli.Command{{{}}}", fields.join(", "));
    var
}

/// One flag, as a `cli.Flag` literal.
fn emit_flag(flag: &SpecFlag, skipped: &mut Skipped) -> Option<String> {
    let Some(long) = flag.long.first() else {
        // urfave takes a name and a list of aliases, all of them spelled without dashes,
        // and decides `-x` from the length. A one-character name is a short flag with no
        // long form — which is expressible — but its `Name` is then what help prints and
        // what `cmd.Bool` looks up, so a spec that has only `-x` becomes a different flag.
        skipped.note("short-only flags");
        return None;
    };

    let mut fields = vec![format!("Name: {}", go_string(long))];
    // urfave has no separate vocabulary for a short form: an alias of one character is
    // matched as `-x`, and the second long form is matched as `--long`. Both go in the
    // same list, which is why nothing is dropped here.
    let aliases: Vec<String> = flag
        .short
        .iter()
        .map(|c| c.to_string())
        .chain(flag.long.iter().skip(1).cloned())
        .collect();
    if !aliases.is_empty() {
        fields.push(format!("Aliases: {}", string_slice(&aliases)));
    }
    if let Some(help) = flag.help.as_deref().or(flag.help_first_line.as_deref()) {
        fields.push(format!("Usage: {}", go_string(help)));
    }
    if flag.hide {
        fields.push("Hidden: true".to_string());
    }
    if flag.required {
        fields.push("Required: true".to_string());
    }
    // A global is in scope for everything below, which urfave spells by *not* marking the
    // flag local. The default is the inherited one, so it is the local flags that say so.
    if !flag.global {
        fields.push("Local: true".to_string());
    }
    if let Some(env) = flag.env.as_deref() {
        fields.push(format!("Sources: cli.EnvVars({})", go_string(env)));
    }

    let kind = match (&flag.arg, flag.count, flag.var) {
        // A counter is a bool flag with somewhere to keep the tally. The destination is
        // per build, as every other part of urfave's model is.
        (None, true, _) => {
            fields.push("Config: cli.BoolConfig{Count: new(int)}".to_string());
            "BoolFlag"
        }
        (None, false, _) => "BoolFlag",
        (Some(_), _, true) => "StringSliceFlag",
        (Some(_), _, false) => {
            if let Some(default) = flag.default.first() {
                fields.push(format!("Value: {}", go_string(default)));
            }
            "StringFlag"
        }
    };

    if flag.negate.is_some() {
        skipped.note("negations (`--no-x` is a flag of its own in urfave)");
    }

    Some(format!("&cli.{kind}{{{}}}", fields.join(", ")))
}

/// One positional, as a `cli.Argument` literal.
fn emit_arg(arg: &SpecArg, skipped: &mut Skipped) -> String {
    let name = go_string(&arg.name);
    if arg.var {
        let min = if arg.required { 1 } else { 0 };
        format!("&cli.StringArgs{{Name: {name}, Min: {min}, Max: -1}}")
    } else {
        if !arg.required {
            // `StringArg` parses one value if there is one and does not mind if there is
            // not, which is what an optional positional means. What it cannot say is that
            // a *required* one is missing — see below — so only that direction is dropped.
            skipped.note("optional positionals (urfave parses one either way)");
        } else {
            skipped.note("required positionals (urfave has no arity check for one value)");
        }
        format!("&cli.StringArg{{Name: {name}}}")
    }
}
