// @generated by usage-cli from cli/usage.usage.kdl
const envVarGenerator = {
  script: ["sh", "-c", "env"],
  postProcess: (output: string) => {
    return output.split("\n").map((l) => ({ name: l.split("=")[0] }));
  },
};

const usageGenerateSpec = (cmds: string[]) => {
  return async (
    context: string[],
    executeCommand: Fig.ExecuteCommandFunction
  ): Promise<Fig.Spec> => {
    const promises = cmds.map(async (cmd): Promise<Fig.Subcommand[]> => {
      try {
        const args = cmd.split(" ");
        const {
          stdout,
          stderr: cmdStderr,
          status: cmdStatus,
        } = await executeCommand({
          command: args[0],
          args: args.splice(1),
        });
        if (cmdStatus !== 0) {
          return [{ name: "error", description: cmdStderr }];
        }
        const {
          stdout: figSpecOut,
          stderr: figSpecStderr,
          status: usageFigStatus,
        } = await executeCommand({
          command: "usage",
          args: ["g", "fig", "--spec", stdout],
        });
        if (usageFigStatus !== 0) {
          return [{ name: "error", description: figSpecStderr }];
        }

        const start_of_json = figSpecOut.indexOf("{");
        const j = figSpecOut.slice(start_of_json);
        return JSON.parse(j).subcommands as Fig.Subcommand[];
      } catch (e) {
        return [{ name: "error", description: e }] as Fig.Subcommand[];
      }
    });

    // eslint-disable-next-line compat/compat
    const results = await Promise.allSettled(promises);
    const subcommands = results
      .filter((p) => p.status === "fulfilled")
      .map((p) => p.value);
    const failed = results
      .filter((p) => p.status === "rejected")
      .map((p) => ({ name: "error", description: p.reason }));

    return { subcommands: [...subcommands.flat(), ...failed] } as Fig.Spec;
  };
};

const completionGeneratorTemplate = (
  argSuggestionBash: string
): Fig.Generator => {
  return {
    custom: async (tokens: string[], executeCommand) => {
      let arg = argSuggestionBash;
      if (tokens.length >= 1) {
        arg = argSuggestionBash.replace(
          "{{words[CURRENT]}}",
          tokens[tokens.length - 1]
        );
      }

      if (tokens.length >= 2) {
        arg = arg.replace(`{{words[PREV]}}`, tokens[tokens.length - 2]);
      }
      const { stdout: text } = await executeCommand({
        command: "sh",
        args: ["-c", arg],
      });
      if (text.trim().length == 0) return [];
      return text.split("\n").map((elm) => ({ name: elm }));
    },
  };
};

const completionSpec: Fig.Spec = {
  name: "usage",
  subcommands: [
    {
      name: "bash",
      description: "Execute a shell script using bash",
      options: [
        {
          name: "-h",
          description: "Print the script's help page instead of running it",
          isRepeatable: false,
        },
        {
          name: "--help",
          description: "Print the script's help page instead of running it",
          isRepeatable: false,
        },
      ],
      args: [
        {
          name: "script",
          description:
            "The script to run; its spec is read from the `#USAGE` comments at the top of the file",
        },
        {
          name: "args",
          description: "Arguments to pass to the script",
          isOptional: true,
          isVariadic: true,
        },
      ],
    },
    {
      name: ["complete-word", "cw"],
      description:
        "Generate shell completion candidates for a partial command line",
      options: [
        {
          name: ["-f", "--file"],
          description:
            'A usage spec file, or a script with a usage shebang; "-" reads stdin',
          isRepeatable: false,
          args: {
            name: "file",
            template: "filepaths",
          },
        },
        {
          name: ["-s", "--spec"],
          description: "The spec itself, as a string, instead of a file",
          isRepeatable: false,
          args: {
            name: "spec",
          },
        },
        {
          name: "--cword",
          description:
            "Index of the word being completed; defaults to the last word",
          isRepeatable: false,
          args: {
            name: "cword",
          },
        },
        {
          name: "--shell",
          description:
            "The shell the candidates are for, which decides how they are quoted",
          isRepeatable: false,
          args: {
            name: "shell",
            suggestions: ["bash", "fish", "nu", "powershell", "zsh"],
          },
        },
        {
          name: ["-h", "--help"],
          description: "Print help",
          isRepeatable: false,
        },
      ],
      args: {
        name: "words",
        description: "The words typed so far, starting with the program name",
        isOptional: true,
        isVariadic: true,
      },
    },
    {
      name: "diff",
      description:
        "Compare two usage specs and report what changed about the interface",
      options: [
        {
          name: ["-f", "--format"],
          description: "Output format",
          isRepeatable: false,
          args: {
            name: "format",
            suggestions: ["text", "json"],
          },
        },
        {
          name: ["-b", "--breaking"],
          description: "Report only breaking changes",
          isRepeatable: false,
        },
        {
          name: "--exit-zero",
          description: "Exit 0 even when there are breaking changes",
          isRepeatable: false,
        },
        {
          name: ["-h", "--help"],
          description: "Print help",
          isRepeatable: false,
        },
      ],
      args: [
        {
          name: "old",
          description:
            'The spec as it was, typically the released one, use "-" to read from stdin',
          template: "filepaths",
        },
        {
          name: "new",
          description: 'The spec as it is now, use "-" to read from stdin',
          template: "filepaths",
        },
      ],
    },
    {
      name: ["exec", "x"],
      description:
        "Run a script through any interpreter, with its parsed arguments as environment variables",
      options: [
        {
          name: "-h",
          description: "Print the script's help page instead of running it",
          isRepeatable: false,
        },
        {
          name: "--help",
          description: "Print the script's help page instead of running it",
          isRepeatable: false,
        },
      ],
      args: [
        {
          name: "command",
          description:
            "The interpreter to run the script with, such as `node` or `python3`",
        },
        {
          name: "bin",
          description: "The script to run",
        },
        {
          name: "args",
          description: "Arguments to pass to the script",
          isOptional: true,
          isVariadic: true,
        },
      ],
    },
    {
      name: "explain",
      description: "Explain what a command line binds to",
      options: [
        {
          name: ["-f", "--file"],
          description:
            'A usage spec file, or a script with a usage shebang; "-" reads stdin',
          isRepeatable: false,
          args: {
            name: "file",
            template: "filepaths",
          },
        },
        {
          name: ["-s", "--spec"],
          description: "The spec itself, as a string, instead of a file",
          isRepeatable: false,
          args: {
            name: "spec",
          },
        },
        {
          name: "--format",
          description: "Output format",
          isRepeatable: false,
          args: {
            name: "format",
            suggestions: ["text", "json"],
          },
        },
        {
          name: "--view",
          description: "A spec-declared executable view to explain",
          isRepeatable: false,
          args: {
            name: "view",
          },
        },
        {
          name: ["-e", "--env"],
          description:
            "Environment to explain against, as KEY=VALUE, repeatable",
          isRepeatable: true,
          args: {
            name: "env",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Print help",
          isRepeatable: false,
        },
      ],
      args: {
        name: "argv",
        description:
          "The command line to explain, starting with the program name",
        isOptional: true,
        isVariadic: true,
      },
    },
    {
      name: "fish",
      description: "Execute a shell script using fish",
      options: [
        {
          name: "-h",
          description: "Print the script's help page instead of running it",
          isRepeatable: false,
        },
        {
          name: "--help",
          description: "Print the script's help page instead of running it",
          isRepeatable: false,
        },
      ],
      args: [
        {
          name: "script",
          description:
            "The script to run; its spec is read from the `#USAGE` comments at the top of the file",
        },
        {
          name: "args",
          description: "Arguments to pass to the script",
          isOptional: true,
          isVariadic: true,
        },
      ],
    },
    {
      name: ["generate", "g"],
      description:
        "Generate completions, docs, manpages, SDKs, and parse tables from a usage spec",
      subcommands: [
        {
          name: ["completion", "c"],
          description:
            "Generate a shell completion script for bash, fish, nu, powershell, or zsh",
          options: [
            {
              name: "--install",
              description:
                "Install the script where this shell looks for it, instead of printing it",
              isRepeatable: false,
            },
            {
              name: "--force",
              description:
                "Replace a file at the target path that usage did not write",
              isRepeatable: false,
            },
            {
              name: ["-f", "--file"],
              description:
                'A usage spec file, or a script with a usage shebang; "-" reads stdin',
              isRepeatable: false,
              args: {
                name: "file",
                template: "filepaths",
              },
            },
            {
              name: "--cache-key",
              description:
                "Cache what --usage-cmd prints under this key, so it runs once per key rather than on every Tab; the CLI's version is a good key",
              isRepeatable: false,
              args: {
                name: "cache_key",
              },
            },
            {
              name: "--usage-bin",
              description:
                "The `usage` executable the script calls back to, when it is not `usage` on PATH",
              isRepeatable: false,
              args: {
                name: "usage_bin",
              },
            },
            {
              name: "--usage-cmd",
              description:
                "A command that prints the CLI's spec, run in place of reading --file",
              isRepeatable: false,
              args: {
                name: "usage_cmd",
              },
            },
            {
              name: ["-h", "--help"],
              description: "Print help",
              isRepeatable: false,
            },
          ],
          args: [
            {
              name: "shell",
              description: "The shell to generate the script for",
              suggestions: ["bash", "fish", "nu", "powershell", "zsh"],
            },
            {
              name: "bin",
              description:
                "The name of the CLI being completed, as it is typed at the prompt",
            },
          ],
        },
        {
          name: ["completion-init", "ci"],
          description:
            "Generate a shell init script that completes every usage-shebang script on PATH",
          options: [
            {
              name: "--usage-bin",
              description:
                "The `usage` executable the script calls back to, when it is not `usage` on PATH",
              isRepeatable: false,
              args: {
                name: "usage_bin",
              },
            },
            {
              name: ["-h", "--help"],
              description: "Print help",
              isRepeatable: false,
            },
          ],
          args: {
            name: "shell",
            description: "The shell to generate the script for",
            suggestions: ["bash", "fish", "zsh"],
          },
        },
        {
          name: "fig",
          description: "Generate a Fig completion spec, for Amazon Q and Fig",
          options: [
            {
              name: ["-f", "--file"],
              description:
                'A usage spec file, or a script with a usage shebang; "-" reads stdin',
              isRepeatable: false,
              args: {
                name: "file",
                template: "filepaths",
              },
            },
            {
              name: "--out-file",
              description:
                'Where to write the spec, or "-" for stdout (default)',
              isRepeatable: false,
              args: {
                name: "out_file",
                template: "filepaths",
              },
            },
            {
              name: "--spec",
              description: "The spec itself, as a string, instead of a file",
              isRepeatable: false,
              args: {
                name: "spec",
              },
            },
            {
              name: ["-h", "--help"],
              description: "Print help",
              isRepeatable: false,
            },
          ],
        },
        {
          name: "go",
          description: "Generate Go parse tables from a usage spec",
          options: [
            {
              name: ["-f", "--file"],
              description:
                'A usage spec file, or a script with a usage shebang; "-" reads stdin',
              isRepeatable: false,
              args: {
                name: "file",
                template: "filepaths",
              },
            },
            {
              name: ["-o", "--out-file"],
              description:
                'Where to write the Go source, or "-" for stdout (default)',
              isRepeatable: false,
              args: {
                name: "out_file",
                template: "filepaths",
              },
            },
            {
              name: ["-p", "--package"],
              description:
                "Go package clause for the generated file (defaults to the spec's bin name)",
              isRepeatable: false,
              args: {
                name: "package",
              },
            },
            {
              name: "--spec",
              description: "The spec itself, as a string, instead of a file",
              isRepeatable: false,
              args: {
                name: "spec",
              },
            },
            {
              name: ["-h", "--help"],
              description: "Print help",
              isRepeatable: false,
            },
          ],
        },
        {
          name: "json",
          description: "Print a usage spec as JSON",
          options: [
            {
              name: ["-f", "--file"],
              description:
                'A usage spec file, or a script with a usage shebang; "-" reads stdin',
              isRepeatable: false,
              args: {
                name: "file",
                template: "filepaths",
              },
            },
            {
              name: "--spec",
              description: "The spec itself, as a string, instead of a file",
              isRepeatable: false,
              args: {
                name: "spec",
              },
            },
            {
              name: "--view",
              description: "Render one spec-declared executable view",
              isRepeatable: false,
              args: {
                name: "view",
              },
            },
            {
              name: ["-h", "--help"],
              description: "Print help",
              isRepeatable: false,
            },
          ],
        },
        {
          name: "json-schema",
          description:
            "Generate a JSON Schema for a CLI's config file from its usage spec",
          options: [
            {
              name: ["-f", "--file"],
              description:
                'A usage spec file, or a script with a usage shebang; "-" reads stdin',
              isRepeatable: false,
              args: {
                name: "file",
                template: "filepaths",
              },
            },
            {
              name: "--out-file",
              description: "Write the schema here instead of to stdout",
              isRepeatable: false,
              args: {
                name: "out_file",
                template: "filepaths",
              },
            },
            {
              name: "--spec",
              description: "The spec itself, as a string, instead of a file",
              isRepeatable: false,
              args: {
                name: "spec",
              },
            },
            {
              name: "--title",
              description: "The schema's title, shown by editors",
              isRepeatable: false,
              args: {
                name: "title",
              },
            },
            {
              name: "--url",
              description: "Where the schema is published, for its `$id`",
              isRepeatable: false,
              args: {
                name: "url",
              },
            },
            {
              name: ["-h", "--help"],
              description: "Print help",
              isRepeatable: false,
            },
          ],
        },
        {
          name: ["manpage", "man"],
          description: "Generate a manpage from a usage spec",
          options: [
            {
              name: ["-f", "--file"],
              description:
                'A usage spec file, or a script with a usage shebang; "-" reads stdin',
              isRepeatable: false,
              args: {
                name: "file",
                template: "filepaths",
              },
            },
            {
              name: "--view",
              description: "Render one spec-declared executable view",
              isRepeatable: false,
              args: {
                name: "view",
              },
            },
            {
              name: ["-o", "--out-file"],
              description: 'Output file path, or "-" for stdout (default)',
              isRepeatable: false,
              args: {
                name: "out_file",
                template: "filepaths",
              },
            },
            {
              name: ["-s", "--section"],
              description: "Manual section number (default: 1)",
              isRepeatable: false,
              args: {
                name: "section",
              },
            },
            {
              name: ["-h", "--help"],
              description: "Print help",
              isRepeatable: false,
            },
          ],
        },
        {
          name: ["markdown", "md"],
          description: "Generate Markdown documentation from a usage spec",
          options: [
            {
              name: ["-f", "--file"],
              description:
                'A usage spec file, or a script with a usage shebang; "-" reads stdin',
              isRepeatable: false,
              args: {
                name: "file",
                template: "filepaths",
              },
            },
            {
              name: "--view",
              description: "Render one spec-declared executable view",
              isRepeatable: false,
              args: {
                name: "view",
              },
            },
            {
              name: ["-m", "--multi"],
              description: "Render each subcommand as a separate markdown file",
              isRepeatable: false,
            },
            {
              name: "--html-encode",
              description: "Escape HTML in markdown",
              isRepeatable: false,
            },
            {
              name: "--out-dir",
              description:
                "Directory for the per-command pages (required with --multi)",
              isRepeatable: false,
              args: {
                name: "out_dir",
                template: "folders",
              },
            },
            {
              name: "--out-file",
              description:
                'Output file path for single-file markdown generation, or "-" for stdout (default)',
              isRepeatable: false,
              args: {
                name: "out_file",
                template: "filepaths",
              },
            },
            {
              name: "--replace-pre-with-code-fences",
              description: "Replace `<pre>` tags with markdown code fences",
              isRepeatable: false,
            },
            {
              name: "--url-prefix",
              description:
                "Prefix for the links between pages, such as /cli/reference",
              isRepeatable: false,
              args: {
                name: "url_prefix",
              },
            },
            {
              name: "--template",
              description:
                "Replace a built-in Tera template, as NAME=PATH; the names are spec, index, command, argument, flag, and config",
              isRepeatable: true,
              args: {
                name: "template",
              },
            },
            {
              name: ["-h", "--help"],
              description: "Print help",
              isRepeatable: false,
            },
          ],
        },
        {
          name: "sdk",
          description: "Generate a type-safe SDK from a usage spec",
          options: [
            {
              name: ["-f", "--file"],
              description:
                'A usage spec file, or a script with a usage shebang; "-" reads stdin',
              isRepeatable: false,
              args: {
                name: "file",
                template: "filepaths",
              },
            },
            {
              name: ["-l", "--language"],
              description: "Target language for the SDK",
              isRepeatable: false,
              args: {
                name: "language",
                suggestions: ["typescript", "python"],
              },
            },
            {
              name: ["-o", "--output"],
              description: "Directory to write the SDK into",
              isRepeatable: false,
              args: {
                name: "output",
              },
            },
            {
              name: ["-p", "--package-name"],
              description:
                "Override the package/module name (defaults to spec bin name)",
              isRepeatable: false,
              args: {
                name: "package_name",
              },
            },
            {
              name: "--spec",
              description: "The spec itself, as a string, instead of a file",
              isRepeatable: false,
              args: {
                name: "spec",
              },
            },
            {
              name: ["-h", "--help"],
              description: "Print help",
              isRepeatable: false,
            },
          ],
        },
      ],
      options: [
        {
          name: ["-h", "--help"],
          description: "Print help",
          isRepeatable: false,
        },
      ],
    },
    {
      name: "lint",
      description: "Lint a usage spec for mistakes that still parse",
      options: [
        {
          name: ["-f", "--format"],
          description: "Output format",
          isRepeatable: false,
          args: {
            name: "format",
            suggestions: ["text", "json"],
          },
        },
        {
          name: ["-W", "--warnings-as-errors"],
          description: "Treat warnings as errors",
          isRepeatable: false,
        },
        {
          name: "--sorted",
          description:
            "Also check that subcommands and flags are declared in sorted order",
          isRepeatable: false,
        },
        {
          name: ["-h", "--help"],
          description: "Print help",
          isRepeatable: false,
        },
      ],
      args: {
        name: "file",
        description:
          'A usage spec file, or a script with a usage shebang; "-" reads stdin',
        template: "filepaths",
      },
    },
    {
      name: ["mcp", "mcp-server"],
      description: "Serve a usage spec over the Model Context Protocol",
      options: [
        {
          name: ["-f", "--file"],
          description:
            'A usage spec file, or a script with a usage shebang (not "-": stdin is the MCP transport)',
          isRepeatable: false,
          args: {
            name: "file",
            template: "filepaths",
          },
        },
        {
          name: ["-s", "--spec"],
          description: "The spec itself, as a string, instead of a file",
          isRepeatable: false,
          args: {
            name: "spec",
          },
        },
        {
          name: ["-h", "--help"],
          description: "Print help",
          isRepeatable: false,
        },
      ],
    },
    {
      name: "powershell",
      description: "Execute a shell script using PowerShell",
      options: [
        {
          name: "-h",
          description: "Print the script's help page instead of running it",
          isRepeatable: false,
        },
        {
          name: "--help",
          description: "Print the script's help page instead of running it",
          isRepeatable: false,
        },
      ],
      args: [
        {
          name: "script",
          description:
            "The script to run; its spec is read from the `#USAGE` comments at the top of the file",
        },
        {
          name: "args",
          description: "Arguments to pass to the script",
          isOptional: true,
          isVariadic: true,
        },
      ],
    },
    {
      name: "sponsors",
      description:
        "Show the companies sponsoring usage and the jdx.dev open source tools",
      options: [
        {
          name: ["-h", "--help"],
          description: "Print help",
          isRepeatable: false,
        },
      ],
    },
    {
      name: "zsh",
      description: "Execute a shell script using zsh",
      options: [
        {
          name: "-h",
          description: "Print the script's help page instead of running it",
          isRepeatable: false,
        },
        {
          name: "--help",
          description: "Print the script's help page instead of running it",
          isRepeatable: false,
        },
      ],
      args: [
        {
          name: "script",
          description:
            "The script to run; its spec is read from the `#USAGE` comments at the top of the file",
        },
        {
          name: "args",
          description: "Arguments to pass to the script",
          isOptional: true,
          isVariadic: true,
        },
      ],
    },
  ],
  options: [
    {
      name: "--completions",
      description:
        "Print a completion script for the `usage` CLI itself, for the named shell",
      isRepeatable: false,
      args: {
        name: "completions",
      },
    },
    {
      name: "--usage-spec",
      description: "Print the usage spec for the `usage` CLI itself",
      isRepeatable: false,
    },
    {
      name: ["-h", "--help"],
      description: "Print help",
      isRepeatable: false,
    },
    {
      name: ["-V", "--version"],
      description: "Print version",
      isRepeatable: false,
    },
  ],
};

export default completionSpec;
