// @generated by usage-config-build from `hk.usage.kdl`. Do not edit.
//
// Every setting this CLI has, as consts: there is no second declaration of a setting to
// keep in step with this one, which is the drift this file exists to remove.

pub static SETTINGS_PROPS: &[::usage_config::PropMeta] = &[
    ::usage_config::PropMeta {
        scope: ::usage_config::Scope::Env,
        envs: &["CI"],
        hide: true,
        ..::usage_config::PropMeta::new("ci", ::usage_config::Ty::Bool)
    },
    ::usage_config::PropMeta {
        deprecated: Some("Use jobs instead."),
        renamed_to: Some("jobs"),
        ..::usage_config::PropMeta::new("concurrency", ::usage_config::Ty::Uint)
    },
    ::usage_config::PropMeta {
        help: Some("A \"union\" only hk understands"),
        ..::usage_config::PropMeta::new("either", ::usage_config::Ty::Any)
    },
    ::usage_config::PropMeta {
        merge: ::usage_config::Merge::Union,
        parse: Some(::usage_config::Parser::ListByComma),
        envs: &["HK_EXCLUDE"],
        bindings: &[("pkl", "exclude"), ("pkl", "defaults.exclude")],
        help: Some("Paths to leave alone"),
        ..::usage_config::PropMeta::new("exclude", ::usage_config::Ty::List(&::usage_config::Ty::String))
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::Int(4)),
        envs: &["HK_JOBS", "HK_JOB"],
        deprecated_envs: &["HK_JOBS_OLD"],
        cli: &["--jobs", "-j"],
        bindings: &[("git", "hk.jobs")],
        help: Some("How many jobs to run at once"),
        ..::usage_config::PropMeta::new("jobs", ::usage_config::Ty::Uint)
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::Str("1")),
        choices: &[::usage_config::Const::Int(1), ::usage_config::Const::Int(2)],
        help: Some("Which log format to use"),
        ..::usage_config::PropMeta::new("log_format", ::usage_config::Ty::String)
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::Str("info")),
        envs: &["HK_LOG_LEVEL"],
        ..::usage_config::PropMeta::new("log_level", ::usage_config::Ty::String)
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::Str("all")),
        help: Some("Which files to match"),
        ..::usage_config::PropMeta::new("match", ::usage_config::Ty::String)
    },
    ::usage_config::PropMeta {
        parse: Some(::usage_config::Parser::ListByOsPathSeparator),
        envs: &["HK_PATH"],
        ..::usage_config::PropMeta::new("path", ::usage_config::Ty::List(&::usage_config::Ty::Path))
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::List(&[::usage_config::Const::Int(80), ::usage_config::Const::Int(443)])),
        ..::usage_config::PropMeta::new("ports", ::usage_config::Ty::List(&::usage_config::Ty::Uint))
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::Str("git")),
        choices: &[::usage_config::Const::Str("git"), ::usage_config::Const::Str("patch-file"), ::usage_config::Const::Str("none")],
        help: Some("How to stash before a run"),
        ..::usage_config::PropMeta::new("stash", ::usage_config::Ty::String)
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::Str("prefix")),
        help: Some("How task output is interleaved"),
        ..::usage_config::PropMeta::new("task.output", ::usage_config::Ty::String)
    },
    ::usage_config::PropMeta {
        help: Some("How long to wait, if at all"),
        ..::usage_config::PropMeta::new("timeout", ::usage_config::Ty::Option(&::usage_config::Ty::Duration))
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::Bool(false)),
        scope: ::usage_config::Scope::Global,
        help: Some("Whether this checkout may run its own hooks"),
        ..::usage_config::PropMeta::new("trusted", ::usage_config::Ty::Bool)
    },
    ::usage_config::PropMeta {
        merge: ::usage_config::Merge::Deep,
        help: Some("Rewrite these URL prefixes"),
        ..::usage_config::PropMeta::new("url_replacements", ::usage_config::Ty::Map(&::usage_config::Ty::String))
    },
];

pub const SETTINGS_REGISTRY: ::usage_config::Registry =
    ::usage_config::Registry::new(SETTINGS_PROPS);

/// Each setting's id, which is its position in [`SETTINGS_PROPS`].
pub mod prop {
    use ::usage_config::PropId;

    /// `ci`
    pub const CI: PropId = PropId(0);
    /// `concurrency`
    pub const CONCURRENCY: PropId = PropId(1);
    /// `either` — A "union" only hk understands
    pub const EITHER: PropId = PropId(2);
    /// `exclude` — Paths to leave alone
    pub const EXCLUDE: PropId = PropId(3);
    /// `jobs` — How many jobs to run at once
    pub const JOBS: PropId = PropId(4);
    /// `log_format` — Which log format to use
    pub const LOG_FORMAT: PropId = PropId(5);
    /// `log_level`
    pub const LOG_LEVEL: PropId = PropId(6);
    /// `match` — Which files to match
    pub const MATCH: PropId = PropId(7);
    /// `path`
    pub const PATH: PropId = PropId(8);
    /// `ports`
    pub const PORTS: PropId = PropId(9);
    /// `stash` — How to stash before a run
    pub const STASH: PropId = PropId(10);
    /// `task.output` — How task output is interleaved
    pub const TASK_OUTPUT: PropId = PropId(11);
    /// `timeout` — How long to wait, if at all
    pub const TIMEOUT: PropId = PropId(12);
    /// `trusted` — Whether this checkout may run its own hooks
    pub const TRUSTED: PropId = PropId(13);
    /// `url_replacements` — Rewrite these URL prefixes
    pub const URL_REPLACEMENTS: PropId = PropId(14);
}

/// Every setting, as the types a CLI holds them in.
///
/// Read with [`Settings::read`] from a resolution, which is the only way to build one:
/// the values, and every reason one could not be read, come from the merge.
#[derive(Debug, Clone, PartialEq)]
pub struct Settings {
    pub task: SettingsTask,
    /// (`ci`)
    pub ci: Option<bool>,
    /// A "union" only hk understands
    /// (`either`)
    pub either: Option<::usage_config::Value>,
    /// Paths to leave alone
    /// (`exclude`)
    pub exclude: Option<Vec<String>>,
    /// How many jobs to run at once
    /// (`jobs`)
    pub jobs: u64,
    /// Which log format to use
    /// (`log_format`)
    pub log_format: String,
    /// (`log_level`)
    pub log_level: String,
    /// Which files to match
    /// (`match`)
    pub r#match: String,
    /// (`path`)
    pub path: Option<Vec<::std::path::PathBuf>>,
    /// (`ports`)
    pub ports: Vec<u64>,
    /// How to stash before a run
    /// (`stash`)
    pub stash: String,
    /// How long to wait, if at all
    /// (`timeout`)
    pub timeout: Option<String>,
    /// Whether this checkout may run its own hooks
    /// (`trusted`)
    pub trusted: bool,
    /// Rewrite these URL prefixes
    /// (`url_replacements`)
    pub url_replacements: Option<::std::collections::BTreeMap<String, String>>,
}

/// The `task` settings.
#[derive(Debug, Clone, PartialEq)]
pub struct SettingsTask {
    /// How task output is interleaved
    /// (`task.output`)
    pub output: String,
}

impl Settings {
    /// This resolution's values, as their types.
    ///
    /// Every setting is read before anything is returned, so the error is the whole list of
    /// what is wrong rather than the first thing found.
    pub fn read(
        resolved: &::usage_config::Resolved,
    ) -> ::std::result::Result<Self, ::usage_config::ReadErrors> {
        let mut fold = resolved.fold();
        let read_task_output: Option<String> = fold.required(prop::TASK_OUTPUT);
        let read_ci: Option<bool> = fold.optional(prop::CI);
        let read_either: Option<::usage_config::Value> = fold.optional(prop::EITHER);
        let read_exclude: Option<Vec<String>> = fold.optional(prop::EXCLUDE);
        let read_jobs: Option<u64> = fold.required(prop::JOBS);
        let read_log_format: Option<String> = fold.required(prop::LOG_FORMAT);
        let read_log_level: Option<String> = fold.required(prop::LOG_LEVEL);
        let read_match: Option<String> = fold.required(prop::MATCH);
        let read_path: Option<Vec<::std::path::PathBuf>> = fold.optional(prop::PATH);
        let read_ports: Option<Vec<u64>> = fold.required(prop::PORTS);
        let read_stash: Option<String> = fold.required(prop::STASH);
        let read_timeout: Option<String> = fold.optional(prop::TIMEOUT);
        let read_trusted: Option<bool> = fold.required(prop::TRUSTED);
        let read_url_replacements: Option<::std::collections::BTreeMap<String, String>> = fold.optional(prop::URL_REPLACEMENTS);
        fold.finish()?;
        ::std::result::Result::Ok(Self {
            task: SettingsTask {
                output: read_task_output.expect("`task.output` has a declared default, so the fold has already reported any absence"),
            },
            ci: read_ci,
            either: read_either,
            exclude: read_exclude,
            jobs: read_jobs.expect("`jobs` has a declared default, so the fold has already reported any absence"),
            log_format: read_log_format.expect("`log_format` has a declared default, so the fold has already reported any absence"),
            log_level: read_log_level.expect("`log_level` has a declared default, so the fold has already reported any absence"),
            r#match: read_match.expect("`match` has a declared default, so the fold has already reported any absence"),
            path: read_path,
            ports: read_ports.expect("`ports` has a declared default, so the fold has already reported any absence"),
            stash: read_stash.expect("`stash` has a declared default, so the fold has already reported any absence"),
            timeout: read_timeout,
            trusted: read_trusted.expect("`trusted` has a declared default, so the fold has already reported any absence"),
            url_replacements: read_url_replacements,
        })
    }
}
