// @generated by usage-config-build from `hk.usage.kdl`. Do not edit.
//
// Every setting this CLI has, as consts: there is no second declaration of a setting to
// keep in step with this one, which is the drift this file exists to remove.

pub static SETTINGS_PROPS: &[::usage_config::PropMeta] = &[
    ::usage_config::PropMeta {
        scope: ::usage_config::Scope::Env,
        envs: &["CI"],
        hide: true,
        ..::usage_config::PropMeta::new("ci", ::usage_config::Ty::Bool)
    },
    ::usage_config::PropMeta {
        deprecated: Some("Use jobs instead."),
        renamed_to: Some("jobs"),
        ..::usage_config::PropMeta::new("concurrency", ::usage_config::Ty::Uint)
    },
    ::usage_config::PropMeta {
        help: Some("A \"union\" only hk understands"),
        ..::usage_config::PropMeta::new("either", ::usage_config::Ty::Any)
    },
    ::usage_config::PropMeta {
        merge: ::usage_config::Merge::Union,
        parse: Some(::usage_config::Parser::ListByComma),
        envs: &["HK_EXCLUDE"],
        bindings: &[("pkl", "exclude"), ("pkl", "defaults.exclude")],
        help: Some("Paths to leave alone"),
        ..::usage_config::PropMeta::new("exclude", ::usage_config::Ty::List(&::usage_config::Ty::String))
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::Int(4)),
        envs: &["HK_JOBS", "HK_JOB"],
        bindings: &[("git", "hk.jobs")],
        help: Some("How many jobs to run at once"),
        ..::usage_config::PropMeta::new("jobs", ::usage_config::Ty::Uint)
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::Str("info")),
        envs: &["HK_LOG_LEVEL"],
        ..::usage_config::PropMeta::new("log_level", ::usage_config::Ty::String)
    },
    ::usage_config::PropMeta {
        parse: Some(::usage_config::Parser::ListByOsPathSeparator),
        envs: &["HK_PATH"],
        ..::usage_config::PropMeta::new("path", ::usage_config::Ty::List(&::usage_config::Ty::Path))
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::List(&[::usage_config::Const::Int(80), ::usage_config::Const::Int(443)])),
        ..::usage_config::PropMeta::new("ports", ::usage_config::Ty::List(&::usage_config::Ty::Uint))
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::Str("git")),
        help: Some("How to stash before a run"),
        ..::usage_config::PropMeta::new("stash", ::usage_config::Ty::String)
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::Str("prefix")),
        help: Some("How task output is interleaved"),
        ..::usage_config::PropMeta::new("task.output", ::usage_config::Ty::String)
    },
    ::usage_config::PropMeta {
        help: Some("How long to wait, if at all"),
        ..::usage_config::PropMeta::new("timeout", ::usage_config::Ty::Option(&::usage_config::Ty::Duration))
    },
    ::usage_config::PropMeta {
        default: Some(::usage_config::Const::Bool(false)),
        scope: ::usage_config::Scope::Global,
        help: Some("Whether this checkout may run its own hooks"),
        ..::usage_config::PropMeta::new("trusted", ::usage_config::Ty::Bool)
    },
    ::usage_config::PropMeta {
        merge: ::usage_config::Merge::Deep,
        help: Some("Rewrite these URL prefixes"),
        ..::usage_config::PropMeta::new("url_replacements", ::usage_config::Ty::Map(&::usage_config::Ty::String))
    },
];

pub const SETTINGS_REGISTRY: ::usage_config::Registry =
    ::usage_config::Registry::new(SETTINGS_PROPS);

/// Each setting's id, which is its position in [`SETTINGS_PROPS`].
pub mod prop {
    use ::usage_config::PropId;

    /// `ci`
    pub const CI: PropId = PropId(0);
    /// `concurrency`
    pub const CONCURRENCY: PropId = PropId(1);
    /// `either` — A "union" only hk understands
    pub const EITHER: PropId = PropId(2);
    /// `exclude` — Paths to leave alone
    pub const EXCLUDE: PropId = PropId(3);
    /// `jobs` — How many jobs to run at once
    pub const JOBS: PropId = PropId(4);
    /// `log_level`
    pub const LOG_LEVEL: PropId = PropId(5);
    /// `path`
    pub const PATH: PropId = PropId(6);
    /// `ports`
    pub const PORTS: PropId = PropId(7);
    /// `stash` — How to stash before a run
    pub const STASH: PropId = PropId(8);
    /// `task.output` — How task output is interleaved
    pub const TASK_OUTPUT: PropId = PropId(9);
    /// `timeout` — How long to wait, if at all
    pub const TIMEOUT: PropId = PropId(10);
    /// `trusted` — Whether this checkout may run its own hooks
    pub const TRUSTED: PropId = PropId(11);
    /// `url_replacements` — Rewrite these URL prefixes
    pub const URL_REPLACEMENTS: PropId = PropId(12);
}
