//! The shell scripts that call the hidden completion command.
//!
//! Each is a handful of lines, because the thinking is on the other side: the binary answers with
//! candidates and, when paths belong there, a marker. So a script's whole job is to hand over the
//! line and the cursor, present what comes back the way its shell presents things, and pass the
//! position to the shell's own path completion if the marker appeared.
//!
//! What that replaces is worth stating. mise's current scripts hard-fail unless the separate
//! `usage` CLI is installed, dump a spec into `$XDG_CACHE_HOME` with `mise usage`, prune stale
//! spec files by age, and shell out to `usage complete-word` on every Tab. None of that is here.
//!
//! Where a shell already knows how to do something, it does it: zsh's `compadd` with aligned
//! descriptions, fish's `__fish_complete_path`, PowerShell's `CompletionCompleters`. The one place
//! this file argues with a shell is bash, which needs `compopt -o filenames` set from inside the
//! function because whether paths are involved is not known until the answer comes back.

use crate::complete::Shell;

/// The completion script for `bin` in `shell`, ready to be written to a file or sourced.
///
/// The binary is named rather than found: a script that resolved the binary itself would complete
/// against whichever copy came first on `PATH`, which is not always the one the user is typing.
///
/// Every invocation quotes the name, so one containing a space still *runs*. Registering it is
/// another matter: zsh's `#compdef` line is a magic comment read by `compinit` before any shell
/// quoting happens, and there is nowhere to put a quote in it. A binary whose name is not a
/// single shell word therefore cannot be completed in zsh by anyone, which the assertion says
/// out loud rather than leaving to be discovered at a prompt.
pub fn script(bin: &str, shell: Shell) -> String {
    debug_assert!(
        !bin.contains(char::is_whitespace),
        "a completion script cannot register a binary whose name is not one shell word \
         ({bin:?}): zsh's `#compdef` line has nowhere to put a quote"
    );
    let ident = shell_ident(bin);
    match shell {
        Shell::Bash => bash(bin, &ident),
        Shell::Zsh => zsh(bin, &ident),
        Shell::Fish => fish(bin, &ident),
        Shell::Nu => nu(bin, &ident),
        Shell::PowerShell => powershell(bin),
    }
}

/// A name a shell will accept for a function, derived from a binary's.
///
/// `my-tool` and `my.tool` are ordinary binary names and neither is an identifier, so anything
/// that is not a letter, a digit or an underscore becomes one.
fn shell_ident(bin: &str) -> String {
    let mut out = String::with_capacity(bin.len());
    for c in bin.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    out
}

/// The header every script carries, so nobody edits one by hand twice.
fn header(bin: &str, shell: Shell, comment: &str) -> String {
    format!(
        "{comment} @generated by usage-argv for `{bin} __complete_word__ --shell {}`\n\
         {comment} Do not edit: regenerate it. Needs no other program, and no cached spec —\n\
         {comment} the binary answers from the tables it was compiled with.\n",
        shell.as_str()
    )
}

fn bash(bin: &str, ident: &str) -> String {
    let head = header(bin, Shell::Bash, "#");
    format!(
        r#"{head}
_usage_complete_{ident}() {{
    local __usage_out __usage_line __usage_files=
    # Truncated here rather than passed with an offset: every shell counts a cursor in its own
    # units — characters in a UTF-8 locale for bash and zsh, characters for fish and PowerShell —
    # and a number that means one thing here and another there is a bug waiting for a non-ASCII
    # command line. Cut with the shell's own offset, the units cancel out and what arrives is
    # exactly the text before the cursor.
    __usage_out="$(command '{bin}' __complete_word__ --shell bash \
        --line "${{COMP_LINE:0:$COMP_POINT}}" 2>/dev/null)" || return 1

    COMPREPLY=()
    while IFS= read -r __usage_line; do
        case "$__usage_line" in
            $'\001files') __usage_files=any ;;
            $'\001dirs') __usage_files=dirs ;;
            '') ;;
            *) COMPREPLY+=("$__usage_line") ;;
        esac
    done <<< "$__usage_out"

    if [[ -n $__usage_files ]]; then
        # Set here rather than on `complete`, because whether this position takes a path is not
        # known until the answer comes back. It is what makes bash append a `/` to a directory
        # and stop escaping what it should not.
        compopt -o filenames 2>/dev/null
        local __usage_cur="${{COMP_WORDS[COMP_CWORD]}}" __usage_path
        local -a __usage_paths=()
        if [[ $__usage_files == dirs ]]; then
            while IFS= read -r __usage_path; do __usage_paths+=("$__usage_path"); done \
                < <(compgen -d -- "$__usage_cur")
        else
            while IFS= read -r __usage_path; do __usage_paths+=("$__usage_path"); done \
                < <(compgen -f -- "$__usage_cur")
        fi
        # Guarded, because an empty array expands to one empty word in older bash.
        (( ${{#__usage_paths[@]}} )) && COMPREPLY+=("${{__usage_paths[@]}}")
    fi
}}
complete -F _usage_complete_{ident} '{bin}'
"#,
    )
}

fn zsh(bin: &str, ident: &str) -> String {
    let head = header(bin, Shell::Zsh, "#");
    // `compadd` rather than `_describe`, which groups matches sharing a `:`-separated prefix and
    // shows one per group — so mise's `release:create`, `release:docs-sync` and `release:pr`
    // collapse into a single entry. The display column is built here instead, descriptions
    // aligned to the longest value, which is the presentation the reference arrived at.
    format!(
        r#"{head}#compdef {bin}

_usage_complete_{ident}() {{
    local -a values=() descriptions=() inserts=()
    local __usage_files= __usage_line __usage_menu=0
    # `$BUFFER[1,CURSOR]` is the text before the cursor, cut with zsh's own offset — see the
    # bash script on why the cutting happens here rather than through a `--cursor` argument.
    while IFS= read -r __usage_line; do
        case "$__usage_line" in
            $'\001files') __usage_files=any; continue ;;
            $'\001dirs') __usage_files=dirs; continue ;;
            '') continue ;;
        esac
        local -a parts=("${{(@ps:\t:)__usage_line}}")
        values+=("${{parts[1]}}")
        descriptions+=("${{parts[2]}}")
        inserts+=("${{parts[3]}}")
        # A quoted insert means the value needed quoting, and zsh should offer a menu rather
        # than silently inserting one of several possibilities.
        [[ "${{parts[3]}}" == "'"* ]] && __usage_menu=1
    done < <(command '{bin}' __complete_word__ --shell zsh \
        --line "${{BUFFER[1,CURSOR]}}" 2>/dev/null)

    local __usage_ret=1
    (( __usage_menu )) && compstate[insert]=menu
    if (( ${{#inserts[@]}} )); then
        local -a display=()
        local i max=0 value pad
        for value in "${{values[@]}}"; do
            (( ${{#value}} > max )) && max=${{#value}}
        done
        for (( i = 1; i <= ${{#values[@]}}; i++ )); do
            if [[ -n "${{descriptions[i]}}" ]]; then
                pad=$(( max - ${{#values[i]}} ))
                display+=("${{values[i]}}${{(l:pad:: :)}}  -- ${{descriptions[i]}}")
            else
                display+=("${{values[i]}}")
            fi
        done
        # `-U` because the binary already filtered by the typed prefix, and `-Q` because the
        # inserts are quoted already.
        compadd -l -d display -U -Q -S '' -a inserts && __usage_ret=0
    fi

    case "$__usage_files" in
        any) _files && __usage_ret=0 ;;
        dirs) _files -/ && __usage_ret=0 ;;
    esac
    return $__usage_ret
}}
compdef _usage_complete_{ident} '{bin}'
"#,
    )
}

fn fish(bin: &str, ident: &str) -> String {
    let head = header(bin, Shell::Fish, "#");
    // `commandline -cp` is the line up to the cursor, so the cursor is its length — fish has no
    // separate offset to pass, and needs none.
    format!(
        r#"{head}
function __usage_complete_{ident}
    set -l line (commandline -cp)
    # `commandline -cp` is already cut at the cursor, so there is nothing to say about where
    # the cursor is: the end of what it gives is where the cursor was.
    set -l out (command '{bin}' __complete_word__ --shell fish --line "$line" 2>/dev/null)
    # Built with printf rather than written literally: fish's `case` takes patterns, not
    # computed values, and a control byte is not something to spell twice.
    set -l marker_any (printf '\x01files')
    set -l marker_dirs (printf '\x01dirs')
    set -l files ""
    for entry in $out
        if test "$entry" = "$marker_any"
            set files any
        else if test "$entry" = "$marker_dirs"
            set files dirs
        else if test -n "$entry"
            echo $entry
        end
    end
    # fish's own path completion, which knows about `~`, variables and remote paths.
    switch $files
        case any
            __fish_complete_path (commandline -ct)
        case dirs
            __fish_complete_directories (commandline -ct)
    end
end

# `-f` so fish offers no filenames of its own: this CLI says when they belong, and the function
# produces them itself when they do.
complete -c '{bin}' -f -a '(__usage_complete_{ident})'
"#,
    )
}

fn nu(bin: &str, ident: &str) -> String {
    let head = header(bin, Shell::Nu, "#");
    // nushell's external completer is handed the spans it split, never the line — so the line is
    // put back together from them. Lossless in the direction that matters: nushell has already
    // done the splitting, and re-quoting a span that contains a space says so.
    format!(
        r#"{head}
def --env __usage_complete_{ident} [spans: list<string>] {{
    let line = ($spans | each {{|span|
        if ($span | str contains " ") {{ $'"($span)"' }} else {{ $span }}
    }} | str join " ")
    let out = (^{bin} __complete_word__ --shell nu --line $line | complete)
    if $out.exit_code != 0 {{ return null }}
    let lines = ($out.stdout | lines | where {{|l| $l != "" }})
    let marker = "\u{{1}}"
    let wants_files = ($lines | any {{|l| $l == $marker + "files" or $l == $marker + "dirs" }})
    let candidates = (
        $lines
        | where {{|l| not ($l | str starts-with $marker) }}
        | each {{|l|
            let parts = ($l | split row (char tab))
            {{
                value: ($parts | get 0)
                description: (if ($parts | length) > 1 {{ $parts | get 1 }} else {{ "" }})
            }}
        }}
    )
    # `null` is how a nushell completer says "you do this one", and what it does is complete
    # paths. So an answer that is only the marker returns null rather than nothing, which would
    # mean "there is nothing here".
    if ($candidates | is-empty) and $wants_files {{ null }} else {{ $candidates }}
}}

# Slot this into the external completer nushell already has, if any, rather than replacing it:
# a config that completes several tools should keep completing all of them.
let __usage_previous_{ident} = ($env.config.completions.external.completer? | default null)
$env.config.completions.external.completer = {{|spans|
    if ($spans | get 0) == "{bin}" {{
        __usage_complete_{ident} $spans
    }} else if $__usage_previous_{ident} != null {{
        do $__usage_previous_{ident} $spans
    }} else {{
        null
    }}
}}
"#
    )
}

fn powershell(bin: &str) -> String {
    let head = header(bin, Shell::PowerShell, "#");
    // PowerShell hands over an AST and a cursor position, and has no way for a native completer
    // to say "you take this one" — so its own file completer is called directly, which is the
    // same machinery it would have used.
    format!(
        r#"{head}
Register-ArgumentCompleter -Native -CommandName '{bin}' -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)

    $marker = [char]1
    # `$cursorPosition` is an offset into the whole input buffer while `Extent.Text` is only this
    # command's span, so after a pipeline or a `;` the two do not share an origin. Subtracting the
    # extent's start puts them back on the same footing, and cutting here means no offset has to
    # travel — see the bash script on why.
    $extent = $commandAst.Extent
    $offset = $cursorPosition - $extent.StartOffset
    if ($offset -lt 0) {{ $offset = 0 }}
    if ($offset -gt $extent.Text.Length) {{ $offset = $extent.Text.Length }}
    $line = $extent.Text.Substring(0, $offset)
    $out = @(& '{bin}' __complete_word__ --shell powershell --line $line 2>$null)

    $files = $null
    $results = [System.Collections.Generic.List[System.Management.Automation.CompletionResult]]::new()
    foreach ($entry in $out) {{
        if ([string]::IsNullOrEmpty($entry)) {{ continue }}
        if ($entry -eq ($marker + 'files')) {{ $files = 'any'; continue }}
        if ($entry -eq ($marker + 'dirs')) {{ $files = 'dirs'; continue }}
        $parts = $entry -split "`t", 2
        $value = $parts[0]
        $description = if ($parts.Count -gt 1 -and $parts[1]) {{ $parts[1] }} else {{ $value }}
        $results.Add(
            [System.Management.Automation.CompletionResult]::new(
                $value, $value, 'ParameterValue', $description
            )
        )
    }}

    if ($files) {{
        # PowerShell's own, so that `~`, drive-relative paths and provider paths behave as they
        # do everywhere else in the shell.
        foreach ($path in [System.Management.Automation.CompletionCompleters]::CompleteFilename($wordToComplete)) {{
            if ($files -eq 'dirs' -and -not (Test-Path -Path $path.CompletionText -PathType Container)) {{
                continue
            }}
            $results.Add($path)
        }}
    }}

    $results
}}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_script_names_the_binary_and_the_hidden_command() {
        for shell in [
            Shell::Bash,
            Shell::Zsh,
            Shell::Fish,
            Shell::Nu,
            Shell::PowerShell,
        ] {
            let out = script("mise", shell);
            assert!(out.contains("mise"), "{shell:?}");
            assert!(out.contains("__complete_word__"), "{shell:?}");
            assert!(out.contains("--shell"), "{shell:?}");
            // And nothing about the thing this replaces: no second program, no cached spec.
            assert!(!out.contains("usage complete-word"), "{shell:?}");
            assert!(!out.contains("XDG_CACHE_HOME"), "{shell:?}");
        }
    }

    #[test]
    fn a_binary_name_that_is_not_an_identifier_still_gives_one() {
        // `my-tool` and `my.tool` are ordinary names for a binary and neither can name a shell
        // function, so the function is named after a sanitized version while the *command* keeps
        // its own name.
        let out = script("my-tool", Shell::Bash);
        assert!(out.contains("_usage_complete_my_tool()"), "{out}");
        assert!(
            out.contains(r"complete -F _usage_complete_my_tool 'my-tool'"),
            "{out}"
        );
        // Quoted at every invocation too, so a name needing quotes at least runs — see the
        // assertion in `script` for the one place a quote cannot go.
        assert!(
            out.contains(r"command 'my-tool' __complete_word__"),
            "{out}"
        );
    }
}
