//! Turning a spec into Rust source that declares the same CLI.
//!
//! The output is checked in rather than built by a `build.rs`, for two reasons: the
//! compile-time comparison wants a fixed input to measure, and a generated file in the
//! tree is a diff a reviewer can read when the derive's vocabulary changes.

use super::*;

/// What a spec property turned into, or why it did not.
///
/// Collected rather than warned about one at a time: a spec of mise's size drops
/// enough on the floor that a reader needs the totals, and silence would read as
/// "everything was expressible".
#[derive(Default)]
struct Skipped {
    counts: BTreeMap<&'static str, usize>,
}

impl Skipped {
    fn note(&mut self, what: &'static str) {
        *self.counts.entry(what).or_default() += 1;
    }

    fn report(&self) {
        if self.counts.is_empty() {
            println!("  nothing dropped: the derive expressed the whole spec");
            return;
        }
        println!("  dropped, because the derive cannot express it yet:");
        for (what, n) in &self.counts {
            println!("    {what}: {n}");
        }
    }
}

pub fn generate(spec_path: &Path, out_dir: &Path) {
    let text = std::fs::read_to_string(spec_path)
        .unwrap_or_else(|e| fail(&format!("reading {}: {e}", spec_path.display())));
    let spec: Spec = text
        .parse()
        .unwrap_or_else(|e| fail(&format!("parsing {}: {e}", spec_path.display())));

    let (out, skipped) = render(&spec, spec_path);
    write_crate(out_dir, &spec.bin, &out);

    println!(
        "generated {} from {} ({} commands, {} flags, {} args)",
        out_dir.join("src/lib.rs").display(),
        spec_path.display(),
        count(&spec.cmd, |_| 1),
        count(&spec.cmd, |c| c.flags.len()),
        count(&spec.cmd, |c| c.args.len()),
    );
    skipped.report();
}

/// The crate's source, and what the spec said that it could not carry.
///
/// Separate from [`generate`] so it can be tested without writing anything: what a
/// dialect does with a given spec is the part worth asserting on.
fn render(spec: &Spec, spec_path: &Path) -> (String, Skipped) {
    let mut skipped = Skipped::default();
    let mut names = Names::default();
    let mut out = String::new();

    // Properties of the CLI as a whole that the derive has no way to declare. The root's
    // grammar differs without them: mise sets `default_subcommand run`, so `mise build`
    // routes through `run` there and fills the root's own `[TASK]` here.
    if spec.default_subcommand.is_some() {
        skipped.note("`default_subcommand` on a command");
    }
    if !spec.cmd.mounts.is_empty() {
        skipped.note("a `mount` on a command");
    }
    if spec.cmd.restart_token.is_some() {
        skipped.note("a `restart_token` on a command");
    }

    header(&mut out, spec_path);
    let root = Type::root(&spec.cmd, &mut names);
    emit_command(
        &mut out,
        &spec.cmd,
        &root,
        true,
        &spec.bin,
        &mut skipped,
        &mut names,
    );
    (out, skipped)
}

/// Walk the tree, adding up whatever a closure counts.
fn count(cmd: &SpecCommand, f: impl Fn(&SpecCommand) -> usize + Copy) -> usize {
    f(cmd) + cmd.subcommands.values().map(|c| count(c, f)).sum::<usize>()
}

fn header(out: &mut String, spec_path: &Path) {
    let name = spec_path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();
    out.push_str(&format!(
        "//! A shadow of `{name}`, generated by `cargo run -p xtask -- gen-shadow`.\n\
         //!\n\
         //! Do not edit: regenerate it. It exists to be compiled and parsed against, so\n\
         //! that the parser can be measured at a real CLI's scale rather than a toy one.\n\
         #![allow(dead_code)]\n\n\
         use usage_derive::{{Args, Cli, Subcommands}};\n\n"
    ));
}

/// A generated type's name, and the names already taken.
#[derive(Default)]
struct Names {
    taken: HashSet<String>,
}

impl Names {
    /// A unique CamelCase type name for a command path.
    ///
    /// The path rather than the last segment: mise has `mise settings set` and
    /// `mise config set`, and two `Set` structs would collide. A numeric suffix is the
    /// last resort, for names that collide only after sanitizing.
    fn claim(&mut self, path: &[String], suffix: &str) -> String {
        let base: String = path.iter().map(|p| camel(p)).collect::<String>();
        let mut name = format!("{base}{suffix}");
        if name.is_empty() {
            name = format!("Cmd{suffix}");
        }
        if self.taken.insert(name.clone()) {
            return name;
        }
        for n in 2.. {
            let candidate = format!("{name}{n}");
            if self.taken.insert(candidate.clone()) {
                return candidate;
            }
        }
        unreachable!("the loop above only ends by returning")
    }
}

/// The pair of type names a command needs: its arguments, and its subcommands.
struct Type {
    args: String,
    subcommands: String,
    path: Vec<String>,
}

impl Type {
    fn root(cmd: &SpecCommand, names: &mut Names) -> Self {
        let path = vec![];
        Self {
            args: names.claim(&path, "Cli"),
            subcommands: if cmd.subcommands.is_empty() {
                String::new()
            } else {
                names.claim(&path, "Commands")
            },
            path,
        }
    }

    fn child(parent: &Type, name: &str, cmd: &SpecCommand, names: &mut Names) -> Self {
        let mut path = parent.path.clone();
        path.push(name.to_string());
        Self {
            args: names.claim(&path, "Args"),
            subcommands: if cmd.subcommands.is_empty() {
                String::new()
            } else {
                names.claim(&path, "Commands")
            },
            path,
        }
    }
}

fn emit_command(
    out: &mut String,
    cmd: &SpecCommand,
    ty: &Type,
    is_root: bool,
    bin: &str,
    skipped: &mut Skipped,
    names: &mut Names,
) {
    // Children first, so a reader meets a type before the struct that holds it. The
    // names are claimed here too, since the parent's `subcommand` field needs them.
    let children: Vec<(&String, &SpecCommand, Type)> = cmd
        .subcommands
        .iter()
        // Aliases appear in the map alongside the name they point at; generating both
        // would declare the same command twice. The alias itself is a loss — usage-argv
        // matches aliases, the derive has no way to declare one — so it is counted
        // below rather than passed over in silence.
        .filter(|(name, sub)| sub.name == **name)
        .map(|(name, sub)| (name, sub, Type::child(ty, name, sub, names)))
        .collect();
    for (_, sub, _) in &children {
        for _ in &sub.aliases {
            skipped.note("a command alias");
        }
        for _ in &sub.hidden_aliases {
            skipped.note("a hidden command alias");
        }
        if !sub.mounts.is_empty() {
            skipped.note("a `mount` on a command");
        }
        if sub.restart_token.is_some() {
            skipped.note("a `restart_token` on a command");
        }
    }
    for (_, sub, sub_ty) in &children {
        emit_command(out, sub, sub_ty, false, bin, skipped, names);
    }

    doc_comment(out, cmd.help.as_deref(), cmd.help_long.as_deref(), 0);
    if is_root {
        out.push_str("#[derive(Cli)]\n");
        out.push_str(&format!("#[usage(bin = {:?})]\n", bin));
    } else {
        out.push_str("#[derive(Args)]\n");
    }
    out.push_str(&format!("pub struct {} {{\n", ty.args));

    let mut fields = FieldNames::default();
    for flag in &cmd.flags {
        emit_flag(out, flag, &mut fields, skipped);
    }
    for arg in &cmd.args {
        emit_arg(out, arg, &mut fields, skipped);
    }
    if !ty.subcommands.is_empty() {
        // A bare `T` says a subcommand is required and an `Option<T>` says it may be
        // left out, which is the same distinction the spec draws with
        // `subcommand_required`. Reading it matters: a shadow that accepted
        // `mise bootstrap linux` with nothing after it would be answering a different
        // grammar from the one being measured.
        out.push_str("    #[usage(subcommand)]\n");
        let field = if cmd.subcommand_required {
            format!("    pub command: {},\n", ty.subcommands)
        } else {
            format!(
                "    pub command: ::std::option::Option<{}>,\n",
                ty.subcommands
            )
        };
        out.push_str(&field);
    }
    out.push_str("}\n\n");

    if !ty.subcommands.is_empty() {
        out.push_str("#[derive(Subcommands)]\n");
        out.push_str(&format!("pub enum {} {{\n", ty.subcommands));
        for (name, sub, sub_ty) in &children {
            doc_comment(out, sub.help.as_deref(), None, 1);
            let variant = camel(name);
            if variant != **name {
                out.push_str(&format!("    #[usage(name = {name:?})]\n"));
            }
            out.push_str(&format!("    {variant}({}),\n", sub_ty.args));
        }
        out.push_str("}\n\n");
    }
}

/// Field names already used in the struct being written.
#[derive(Default)]
struct FieldNames {
    taken: HashSet<String>,
}

impl FieldNames {
    fn claim(&mut self, from: &str) -> String {
        let mut name = snake(from);
        if name.is_empty() || name.chars().next().is_some_and(|c| c.is_ascii_digit()) {
            name = format!("v{name}");
        }
        if is_keyword(&name) {
            name = format!("{name}_");
        }
        if self.taken.insert(name.clone()) {
            return name;
        }
        for n in 2.. {
            let candidate = format!("{name}_{n}");
            if self.taken.insert(candidate.clone()) {
                return candidate;
            }
        }
        unreachable!("the loop above only ends by returning")
    }
}

fn emit_flag(out: &mut String, flag: &SpecFlag, fields: &mut FieldNames, skipped: &mut Skipped) {
    let Some(long) = flag.long.first() else {
        // A short-only flag: the derive takes `short` on its own, so this is only
        // reached by a flag with neither, which is not a flag.
        if flag.short.is_empty() {
            skipped.note("a flag with no long or short form");
            return;
        }
        return emit_flag_with(out, flag, None, fields, skipped);
    };
    emit_flag_with(out, flag, Some(long.clone()), fields, skipped)
}

fn emit_flag_with(
    out: &mut String,
    flag: &SpecFlag,
    long: Option<String>,
    fields: &mut FieldNames,
    skipped: &mut Skipped,
) {
    let field = fields.claim(long.as_deref().unwrap_or(&flag.name));
    doc_comment(out, flag.help.as_deref(), flag.help_long.as_deref(), 1);

    let mut opts: Vec<String> = Vec::new();
    // Written out rather than bare, because the field name may have been sanitized —
    // `--type` becomes `type_`, and a bare `long` would rename the flag.
    if let Some(long) = &long {
        opts.push(format!("long = {long:?}"));
    }
    if let Some(short) = flag.short.first() {
        opts.push(format!("short = {short:?}"));
    }
    if flag.long.len() > 1 || flag.short.len() > 1 {
        skipped.note("a flag's second long or short form");
    }
    if let Some(negate) = &flag.negate {
        opts.push(format!("negate = {negate:?}"));
    }
    if flag.global {
        opts.push("global".into());
    }
    if flag.hide {
        opts.push("hide".into());
    }
    if flag.count {
        opts.push("count".into());
    }
    if let Some(env) = &flag.env {
        opts.push(format!("env = {env:?}"));
    }
    if let Some(heading) = &flag.help_heading {
        opts.push(format!("help_heading = {heading:?}"));
    }
    if !flag.overrides.is_empty() {
        opts.push(selector_list("overrides", &flag.overrides));
    }
    if !flag.conflicts.is_empty() {
        opts.push(selector_list("conflicts", &flag.conflicts));
    }
    if !flag.required_if.is_empty() {
        opts.push(selector_list("required_if", &flag.required_if));
    }

    let arg = flag.arg.as_ref();
    let ty = match (arg, flag.count) {
        (_, true) => "u8",
        (None, _) => "bool",
        (Some(arg), _) => {
            if let Some(choices) = &arg.choices {
                let list = choices
                    .choices
                    .iter()
                    .map(|c| format!("{c:?}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                opts.push(format!("choices({list})"));
            }
            // The spec allows several defaults; the derive takes one, since a field
            // holds one value until typed values arrive.
            let defaults = if arg.default.is_empty() {
                &flag.default
            } else {
                &arg.default
            };
            // Not on a collecting field: the derive refuses a default it would write
            // into the spec and then never apply.
            let collects = flag.var || arg.var;
            if !collects {
                if let Some(default) = defaults.first() {
                    opts.push(format!("default = {default:?}"));
                }
                if defaults.len() > 1 {
                    skipped.note("a flag's second and later defaults");
                }
            } else if !defaults.is_empty() {
                skipped.note("a default on a flag that collects values");
            }
            if flag.var || arg.var {
                if flag.var {
                    opts.push("var".into());
                }
                if arg.var {
                    // A variadic argument on a flag: one occurrence taking several
                    // values, which is a different claim from a repeatable flag.
                    opts.push("variadic".into());
                }
                if let Some(min) = arg.var_min {
                    opts.push(format!("var_min = {min}"));
                }
                if let Some(max) = arg.var_max {
                    opts.push(format!("var_max = {max}"));
                }
                "::std::vec::Vec<::std::string::String>"
            } else if flag.required {
                "::std::string::String"
            } else {
                "::std::option::Option<::std::string::String>"
            }
        }
    };
    // `required_unless` needs somewhere to put "absent", so it only goes on an
    // `Option`. A required flag that also carries one is a contradiction the spec
    // allows and the derive does not.
    if !flag.required_unless.is_empty() {
        if ty.starts_with("::std::option::Option") {
            opts.push(selector_list("required_unless", &flag.required_unless));
        } else {
            skipped.note("`required_unless` on a flag whose type is always filled");
        }
    }
    if flag.required && arg.is_none() {
        skipped.note("`required` on a flag that takes no value");
    }

    writeln!(out, "    #[usage({})]", opts.join(", ")).expect("writing to a String");
    writeln!(out, "    pub {field}: {ty},").expect("writing to a String");
}

fn emit_arg(out: &mut String, arg: &SpecArg, fields: &mut FieldNames, skipped: &mut Skipped) {
    let field = fields.claim(&arg.name);
    doc_comment(out, arg.help.as_deref(), arg.help_long.as_deref(), 1);

    let mut opts: Vec<String> = vec!["arg".into(), format!("name = {:?}", arg.name)];
    if arg.hide {
        opts.push("hide".into());
    }
    // An argument can be backed by an environment variable and grouped under a heading
    // just as a flag can, and both reach `ArgMeta` — leaving them out made the shadow's
    // grammar quietly differ from the spec's for any spec that used them.
    if let Some(env) = &arg.env {
        opts.push(format!("env = {env:?}"));
    }
    if let Some(heading) = &arg.help_heading {
        opts.push(format!("help_heading = {heading:?}"));
    }
    if let Some(choices) = &arg.choices {
        let list = choices
            .choices
            .iter()
            .map(|c| format!("{c:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        opts.push(format!("choices({list})"));
    }
    // A default on a collecting field is refused by the derive: it would be written into
    // the spec and then never applied, which is worse than not saying it.
    if !arg.var {
        if let Some(default) = arg.default.first() {
            opts.push(format!("default = {default:?}"));
        }
        if arg.default.len() > 1 {
            skipped.note("an argument's second and later defaults");
        }
    } else if !arg.default.is_empty() {
        skipped.note("a default on a variadic argument");
    }
    match arg.double_dash {
        // The default: a `--` is allowed and changes nothing about where words land.
        usage::SpecDoubleDashChoices::Optional => {}
        usage::SpecDoubleDashChoices::Required => opts.push("double_dash = \"required\"".into()),
        usage::SpecDoubleDashChoices::Automatic => {
            skipped.note("`double_dash = \"automatic\"` on an argument")
        }
        usage::SpecDoubleDashChoices::Preserve => {
            skipped.note("`double_dash = \"preserve\"` on an argument")
        }
    }

    let ty = if arg.var {
        if let Some(min) = arg.var_min {
            opts.push(format!("var_min = {min}"));
        }
        if let Some(max) = arg.var_max {
            opts.push(format!("var_max = {max}"));
        }
        "::std::vec::Vec<::std::string::String>"
    } else if arg.required {
        "::std::string::String"
    } else {
        "::std::option::Option<::std::string::String>"
    };

    writeln!(out, "    #[usage({})]", opts.join(", ")).expect("writing to a String");
    writeln!(out, "    pub {field}: {ty},").expect("writing to a String");
}

/// `conflicts("--a", "--b")`, or `conflicts = "--a"` for one.
fn selector_list(option: &str, selectors: &[String]) -> String {
    if let [one] = selectors {
        return format!("{option} = {one:?}");
    }
    let list = selectors
        .iter()
        .map(|s| format!("{s:?}"))
        .collect::<Vec<_>>()
        .join(", ");
    format!("{option}({list})")
}

/// Help text as a doc comment, which is how the derive reads it.
fn doc_comment(out: &mut String, help: Option<&str>, long: Option<&str>, depth: usize) {
    let indent = "    ".repeat(depth);
    let Some(help) = help.filter(|h| !h.trim().is_empty()) else {
        // Every generated item gets one, so the shadow does not depend on whether the
        // derive requires help text.
        writeln!(out, "{indent}/// Undocumented").expect("writing to a String");
        return;
    };
    for line in help.lines() {
        writeln!(out, "{indent}/// {}", escape_doc(line)).expect("writing to a String");
    }
    // The long form is the whole comment, so it follows a blank line — and only when it
    // says something the short form did not.
    if let Some(long) = long.filter(|l| l.trim() != help.trim() && !l.trim().is_empty()) {
        writeln!(out, "{indent}///").expect("writing to a String");
        for line in long.lines() {
            writeln!(out, "{indent}/// {}", escape_doc(line)).expect("writing to a String");
        }
    }
}

/// Help text, as a doc comment can carry it.
///
/// Verbatim but for carriage returns. The crate turns doctests off, so a code fence or
/// an indented example in help text is text rather than something to compile — and a
/// shadow is more useful the closer its help is to the real thing.
fn escape_doc(line: &str) -> String {
    line.replace('\r', "")
}

fn write_crate(dir: &Path, bin: &str, lib: &str) {
    let src = dir.join("src");
    std::fs::create_dir_all(&src)
        .unwrap_or_else(|e| fail(&format!("creating {}: {e}", src.display())));
    let name = format!("shadow-{}", snake(bin).replace('_', "-"));
    let manifest = format!(
        "# Generated by `cargo run -p xtask -- gen-shadow`. Do not edit.\n\
         [package]\n\
         name = {name:?}\n\
         version = \"0.0.0\"\n\
         edition = \"2021\"\n\
         publish = false\n\n\
         [lib]\n\
         # The doc comments are copied help text, and mise's help is full of indented\n\
         # examples — which Rust would otherwise compile as doctests.\n\
         doctest = false\n\n\
         [dependencies]\n\
         usage-argv = {{ path = \"../../../argv\", features = [\"spec\"] }}\n\
         usage-derive = {{ path = \"../../../derive\" }}\n\n\
         [lints.rust]\n\
         # The shadow is generated, so a warning here is a message to the generator\n\
         # rather than to a reader of this crate.\n\
         missing_docs = \"allow\"\n"
    );
    write(&dir.join("Cargo.toml"), &manifest);
    let lib_path = src.join("lib.rs");
    write(&lib_path, lib);
    // Formatted here rather than left to whoever notices: the file is checked in, so
    // `cargo fmt --check` sees it, and help text copied out of a spec carries trailing
    // whitespace on its blank lines.
    rustfmt(&lib_path);
}

fn rustfmt(path: &Path) {
    match std::process::Command::new("rustfmt")
        .args(["--edition", "2021"])
        .arg(path)
        .status()
    {
        Ok(status) if status.success() => {}
        Ok(status) => fail(&format!("rustfmt exited with {status}")),
        Err(e) => fail(&format!("running rustfmt: {e}")),
    }
}

fn write(path: &Path, contents: &str) {
    std::fs::write(path, contents)
        .unwrap_or_else(|e| fail(&format!("writing {}: {e}", path.display())));
}

fn camel(s: &str) -> String {
    s.split(|c: char| !c.is_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => format!("{}{}", first.to_ascii_uppercase(), chars.as_str()),
                None => String::new(),
            }
        })
        .collect()
}

fn snake(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if c.is_alphanumeric() {
            out.extend(c.to_lowercase());
        } else if !out.ends_with('_') && !out.is_empty() {
            out.push('_');
        }
    }
    out.trim_end_matches('_').to_string()
}

/// Rust keywords, which a spec is free to use as a flag name — mise has `--type`.
fn is_keyword(name: &str) -> bool {
    const KEYWORDS: &[&str] = &[
        "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move",
        "mut", "pub", "ref", "return", "self", "static", "struct", "super", "trait", "true", "try",
        "type", "union", "unsafe", "use", "where", "while", "yield",
    ];
    KEYWORDS.contains(&name)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rendered(spec: &str) -> (String, Skipped) {
        let spec: Spec = spec.parse().expect("valid spec");
        render(&spec, Path::new("probe.usage.kdl"))
    }

    #[test]
    fn an_argument_carries_its_env_and_heading() {
        // Not exercised by mise's spec, which puts `env` only on flags — so it is
        // asserted here rather than assumed from a generated file that happens not to
        // contain one.
        let (out, _) = rendered(
            "name \"ex\"\nbin \"ex\"\narg \"[file]\" env=\"EX_FILE\" help_heading=\"Input\"\n",
        );
        assert!(out.contains(r#"env = "EX_FILE""#), "{out}");
        assert!(out.contains(r#"help_heading = "Input""#), "{out}");
    }

    #[test]
    fn a_required_subcommand_is_not_an_option() {
        let (out, _) = rendered(
            "name \"ex\"\nbin \"ex\"\ncmd \"outer\" subcommand_required=#true {\n  cmd \"inner\"\n}\n",
        );
        assert!(
            out.contains("pub command: OuterCommands,"),
            "a required subcommand should not be an Option: {out}"
        );

        let (out, _) = rendered("name \"ex\"\nbin \"ex\"\ncmd \"outer\" {\n  cmd \"inner\"\n}\n");
        assert!(
            out.contains("pub command: ::std::option::Option<OuterCommands>,"),
            "an optional subcommand should be: {out}"
        );
    }

    #[test]
    fn what_cannot_be_expressed_is_counted() {
        let (_, skipped) = rendered(
            "name \"ex\"\nbin \"ex\"\ndefault_subcommand \"go\"\ncmd \"go\" {\n  alias \"g\"\n}\n",
        );
        assert_eq!(skipped.counts.get("a command alias"), Some(&1));
        assert_eq!(
            skipped.counts.get("`default_subcommand` on a command"),
            Some(&1)
        );
    }
}
