//! The spec's settings written out as `const` Rust.
//!
//! Two rules run through all of it. Nothing is guessed: a declaration this crate cannot represent
//! faithfully is refused rather than approximated, because an approximation compiles and then
//! misbehaves at run time in the author's users' hands. And every problem is collected, because an
//! author fixing a registry wants the list rather than one round trip per mistake.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use usage::spec::config::{
    SpecConfig, SpecConfigMerge, SpecConfigProp, SpecConfigScope, SpecConfigValue,
};
use usage::spec::config_type::{Base, SpecConfigType};

/// The generated registry, or everything wrong with it.
pub(crate) fn registry(config: &SpecConfig, name: &str) -> Result<String, Vec<String>> {
    let mut problems = Vec::new();
    let props: Vec<(&String, &SpecConfigProp)> = config.props.iter().collect();

    check_keys(&props, &mut problems);
    check_renames(&props, &mut problems);
    let idents = identifiers(&props, &mut problems);

    let mut body = String::new();
    for (key, prop) in &props {
        let _ = writeln!(body, "{}", prop_meta(key, prop, &mut problems));
    }

    let settings = crate::settings::settings(&props, &idents, &mut problems);

    if !problems.is_empty() {
        return Err(problems);
    }

    let mut out = String::new();
    // The name is a file name, or whatever a caller passed to `source_of_spec`, and it goes into a
    // *line* comment: a newline in it ends that comment and everything after it reads as code. The
    // same rule the keys in this file follow, and the same reason.
    let name = one_line(name);
    let _ = writeln!(
        out,
        "// @generated by usage-config-build from `{name}`. Do not edit.\n\
         //\n\
         // Every setting this CLI has, as consts: there is no second declaration of a setting to\n\
         // keep in step with this one, which is the drift this file exists to remove."
    );
    let _ = writeln!(
        out,
        "\npub static SETTINGS_PROPS: &[::usage_config::PropMeta] = &[\n{body}];"
    );
    let _ = writeln!(
        out,
        "\npub const SETTINGS_REGISTRY: ::usage_config::Registry =\n    \
         ::usage_config::Registry::new(SETTINGS_PROPS);"
    );

    // Ids as consts, because a `PropId` *is* the index into the table above — so generated code
    // reads a setting without looking its name up, and a typo in a key is a compile error rather
    // than a `None` at run time.
    let _ = writeln!(
        out,
        "\n/// Each setting's id, which is its position in [`SETTINGS_PROPS`].\n\
         pub mod prop {{\n    \
         use ::usage_config::PropId;\n"
    );
    for (index, ((key, prop), ident)) in props.iter().zip(&idents).enumerate() {
        // Both through `one_line`: a doc comment is a line, and a key can hold a newline as easily
        // as help can — after which the rest of the key is code.
        let key = one_line(key);
        if let Some(help) = prop.help.as_deref() {
            let _ = writeln!(out, "    /// `{key}` — {}", one_line(help));
        } else {
            let _ = writeln!(out, "    /// `{key}`");
        }
        let _ = writeln!(out, "    pub const {ident}: PropId = PropId({index});");
    }
    let _ = writeln!(out, "}}");
    out.push_str(&settings);
    Ok(out)
}

/// One `PropMeta`, as the struct-update form: a field this crate does not set is whatever
/// `PropMeta::new` says it is, so a field added to the runtime does not break generated code.
fn prop_meta(key: &str, prop: &SpecConfigProp, problems: &mut Vec<String>) -> String {
    let mut fields = String::new();
    if let Some(default) = default_const(key, prop, problems) {
        let _ = writeln!(fields, "        default: Some({default}),");
    }
    match prop.merge {
        SpecConfigMerge::Replace => {}
        SpecConfigMerge::Union => {
            let _ = writeln!(fields, "        merge: ::usage_config::Merge::Union,");
        }
        SpecConfigMerge::Deep => {
            let _ = writeln!(fields, "        merge: ::usage_config::Merge::Deep,");
        }
    }
    match prop.scope {
        SpecConfigScope::Any => {}
        SpecConfigScope::Global => {
            let _ = writeln!(fields, "        scope: ::usage_config::Scope::Global,");
        }
        SpecConfigScope::Env => {
            let _ = writeln!(fields, "        scope: ::usage_config::Scope::Env,");
        }
    }
    if let Some(parse) = prop.parse.as_deref() {
        match parser(parse) {
            Some(variant) => {
                let _ = writeln!(
                    fields,
                    "        parse: Some(::usage_config::Parser::{variant}),"
                );
            }
            // Not carried as an extension and not dropped: a spec that names a parser nothing
            // implements would resolve values by a rule that does not exist, and every layer
            // handing over text would produce one item where the author wrote several.
            None => problems.push(format!(
                "`{key}` names the parser `{parse}`, which is not one of: {}",
                PARSERS
                    .iter()
                    .map(|(name, _)| *name)
                    .collect::<Vec<_>>()
                    .join(", ")
            )),
        }
    }
    let envs = environment(prop);
    if !envs.is_empty() {
        let list: Vec<String> = envs.iter().map(|env| rust_str(env)).collect();
        let _ = writeln!(fields, "        envs: &[{}],", list.join(", "));
    }
    if !prop.cli.is_empty() {
        let flags: Vec<String> = prop.cli.iter().map(|flag| rust_str(flag)).collect();
        let _ = writeln!(fields, "        cli: &[{}],", flags.join(", "));
    }
    if !prop.bindings.is_empty() {
        let mut pairs = Vec::new();
        for (kind, keys) in &prop.bindings {
            for bound in keys {
                pairs.push(format!("({}, {})", rust_str(kind), rust_str(bound)));
            }
        }
        let _ = writeln!(fields, "        bindings: &[{}],", pairs.join(", "));
    }
    if !prop.choices.is_empty() {
        let values: Vec<String> = prop.choices.iter().map(|c| value_const(&c.value)).collect();
        let _ = writeln!(fields, "        choices: &[{}],", values.join(", "));
    }
    if prop.hide {
        let _ = writeln!(fields, "        hide: true,");
    }
    if let Some(why) = prop.deprecated.as_deref() {
        let _ = writeln!(fields, "        deprecated: Some({}),", rust_str(why));
    }
    if let Some(to) = prop.renamed_to.as_deref() {
        let _ = writeln!(fields, "        renamed_to: Some({}),", rust_str(to));
    }
    if let Some(help) = prop.help.as_deref() {
        let _ = writeln!(fields, "        help: Some({}),", rust_str(help));
    }
    let new = format!(
        "::usage_config::PropMeta::new({}, {})",
        rust_str(key),
        ty(key, prop.value_type.as_ref(), problems),
    );
    // A setting with nothing but a key and a type is written as the call itself: the update form
    // with no fields in it is the same value spelled twice, and clippy says so.
    if fields.is_empty() {
        return format!("    {new},");
    }
    format!("    ::usage_config::PropMeta {{\n{fields}        ..{new}\n    }},")
}

/// The runtime `Ty` expression for a declared type.
///
/// Borrowed inners are fine in a `const`: `Ty::List(&Ty::String)` promotes, which is why the
/// runtime's type is shaped this way.
fn ty(key: &str, declared: Option<&SpecConfigType>, problems: &mut Vec<String>) -> String {
    let Some(declared) = declared else {
        // No `type=` at all. The spec's own default is a string, and saying so beats inventing
        // something cleverer for a property whose author did not say.
        return "::usage_config::Ty::String".to_string();
    };
    match declared {
        SpecConfigType::Base(base) => base_ty(base).to_string(),
        SpecConfigType::List(inner) => format!(
            "::usage_config::Ty::List(&{})",
            ty(key, Some(inner), problems)
        ),
        SpecConfigType::Set(inner) => format!(
            "::usage_config::Ty::Set(&{})",
            ty(key, Some(inner), problems)
        ),
        SpecConfigType::Option(inner) => {
            format!(
                "::usage_config::Ty::Option(&{})",
                ty(key, Some(inner), problems)
            )
        }
        SpecConfigType::Map(k, value) => {
            // A table's keys are text in every format a settings file is written in, so a map
            // keyed by anything else is a promise the runtime cannot keep — and one it would keep
            // *quietly*, handing the CLI string keys for a `map<int, …>`.
            if !matches!(k, Base::String | Base::Custom(_)) {
                problems.push(format!(
                    "`{key}` is a `map<{k}, …>`, and a settings table's keys are text: \
                     write `map<string, …>`"
                ));
            }
            format!(
                "::usage_config::Ty::Map(&{})",
                ty(key, Some(value), problems)
            )
        }
        // A union, or a name this usage does not know: the spec has said usage cannot decide what
        // belongs here, and `Any` is the runtime's word for exactly that — nothing coerced, nothing
        // refused, the field's own type the only judge.
        SpecConfigType::Union(_) => "::usage_config::Ty::Any".to_string(),
    }
}

fn base_ty(base: &Base) -> &'static str {
    match base {
        Base::Bool => "::usage_config::Ty::Bool",
        Base::String => "::usage_config::Ty::String",
        Base::Int => "::usage_config::Ty::Int",
        Base::Uint => "::usage_config::Ty::Uint",
        Base::Float => "::usage_config::Ty::Float",
        Base::Path => "::usage_config::Ty::Path",
        Base::Url => "::usage_config::Ty::Url",
        Base::Duration => "::usage_config::Ty::Duration",
        Base::Object => "::usage_config::Ty::Object",
        Base::Custom(_) => "::usage_config::Ty::Any",
    }
}

/// The declared default as a `Const`, or nothing when there is none.
fn default_const(key: &str, prop: &SpecConfigProp, problems: &mut Vec<String>) -> Option<String> {
    let has_default = prop.default.is_some() || !prop.default_list.is_empty();
    // Asked before either form of default is returned, because a *list* default returned early and
    // skipped this — the one shape of the mistake that was generated instead of refused.
    //
    // An old name that carries a default its replacement does not have would seed a value under a
    // key nothing reads: the merge folds a rename to its target, whose own default is what shows
    // up. Left to run time it is a warning on every run of a shipped binary for a mistake only the
    // author can fix, so it is refused here.
    if let (Some(to), true) = (prop.renamed_to.as_deref(), has_default) {
        problems.push(format!(
            "`{key}` is renamed to `{to}` and declares a default of its own: put the default on \
             the setting that replaced it"
        ));
    }
    // Both forms at once is something the spec accepts and nothing can mean: returning the list and
    // ignoring the scalar dropped a value the author wrote, and I had claimed here that the parser
    // refused it — it does not. I checked.
    if prop.default.is_some() && !prop.default_list.is_empty() {
        problems.push(format!(
            "`{key}` declares a default twice, as `default=` and as a `default` node: keep one"
        ));
    }
    // Anything declared here that the declared type cannot read is a value nothing can ever hold: a
    // `choice` nobody can pick — `choice 1` under `type="bool"`, which reads booleans and their
    // spellings and not numbers — or a default that is seeded straight into the resolution and then
    // read by nothing, since a seeded default passes through no coercion at all.
    let scalar = scalar_ty(prop.value_type.as_ref());
    let mut unreadable = Vec::new();
    for (what, value) in prop
        .default
        .iter()
        .chain(prop.default_list.iter())
        .map(|value| ("defaults to", value))
        .chain(prop.choices.iter().map(|c| ("has a choice", &c.value)))
    {
        if scalar.coerce(runtime_value(value)).is_err() {
            unreadable.push(what);
            problems.push(format!(
                "`{key}` {what} `{}`, which is not {}",
                display(value),
                scalar.describe()
            ));
        }
    }

    // A declared default the declared choices do not allow. At run time it is seeded as the bottom
    // layer and read by whatever holds it, so this is the only place it can be caught at all.
    //
    // Compared only when every choice is one a value could be: against a choice nothing can read,
    // "not one of the values it allows" is a second message for the same mistake, and it blames the
    // wrong end of it.
    if !prop.choices.is_empty() && unreadable.is_empty() {
        // Read the way the run time will read them — through the same `Ty::coerce` — because that is
        // the only comparison that means anything: a spec writes `default="1"` beside `choice 1`, or
        // `choice "yes"` under `type="bool"`, and neither is a mismatch once both are the declared
        // type. Comparing spec literals refused those; comparing only same-shaped literals let
        // `default="3"` beside `choice 1` through, and a *seeded* default never passes the check a
        // supplied value does, so it would have become the effective value with nothing said.
        let allowed = |value: &SpecConfigValue| {
            let target = scalar.coerce(runtime_value(value));
            prop.choices.iter().any(|choice| {
                match (&target, scalar.coerce(runtime_value(&choice.value))) {
                    (Ok(value), Ok(coerced)) if *value == coerced => true,
                    // Coercion did not settle it: compare what the two are written as, exactly as the
                    // run time does. `any` is where that matters — it coerces nothing, so a union's
                    // `choice 1` and a `default="1"` stay an integer and a string, and stopping at
                    // the arm above would refuse a spec the run time accepts.
                    _ => display(value) == display(&choice.value),
                }
            })
        };
        // A list default under a type that declares no items is one value, not several: `any` takes
        // a list perfectly well, and a scalar choice is not one however many items it has. Checked
        // item by item, `default 1 2` beside `choice 1` and `choice 2` passed — and then the whole
        // list is what a seeded default *is*, refused by its own choices and never checked again.
        let declares_items = declares_items(prop.value_type.as_ref());
        if !declares_items && !prop.default_list.is_empty() {
            let written = prop
                .default_list
                .iter()
                .map(display)
                .collect::<Vec<_>>()
                .join(",");
            problems.push(format!(
                "`{key}` defaults to `{written}`, which is not one of the values it allows: {}",
                prop.choices
                    .iter()
                    .map(|c| display(&c.value))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        let items = match declares_items {
            true => prop.default_list.as_slice(),
            false => &[],
        };
        for value in prop.default.iter().chain(items.iter()) {
            if !allowed(value) {
                problems.push(format!(
                    "`{key}` defaults to `{}`, which is not one of the values it allows: {}",
                    display(value),
                    prop.choices
                        .iter()
                        .map(|c| display(&c.value))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
        }
    }
    // A list default is a child node rather than a value, and either may be the one that is there.
    if !prop.default_list.is_empty() {
        let items: Vec<String> = prop
            .default_list
            .iter()
            .map(|value| coerced_const(scalar, value))
            .collect();
        return Some(format!(
            "::usage_config::Const::List(&[{}])",
            items.join(", ")
        ));
    }
    prop.default
        .as_ref()
        .map(|value| coerced_const(scalar, value))
}

/// A declared default as the value its type says it is.
///
/// Emitted *coerced*, because a default is seeded straight into the resolution and passes through no
/// coercion on the way: `default "yes"` under `list<bool>` is a boolean by the time anything reads
/// it, and emitted as the string it was written as, the read fails on a registry this crate had just
/// accepted. A value the type cannot read is refused above, so this only ever converts what the run
/// time would have converted itself.
///
/// A *scalar* default arrives already converted — the spec's own parser reads it as the declared
/// type — so for that one this is belt and braces, and only the list form is observably fixed by it.
/// Applied to both because which of them the parser happens to cover is not something this should
/// depend on.
///
/// Choices are *not* put through this: they are documentation as much as values — the message says
/// "one of yes, no" because that is what a user may write — and the comparison coerces them at the
/// moment it needs them.
fn coerced_const(ty: usage_config::Ty, value: &SpecConfigValue) -> String {
    match ty.coerce(runtime_value(value)) {
        Ok(usage_config::Value::Bool(b)) => format!("::usage_config::Const::Bool({b})"),
        Ok(usage_config::Value::Int(i)) => format!("::usage_config::Const::Int({i})"),
        Ok(usage_config::Value::Float(f)) => format!("::usage_config::Const::Float({f:?})"),
        Ok(usage_config::Value::String(s)) => {
            format!("::usage_config::Const::Str({})", rust_str(&s))
        }
        // A collection cannot come out of coercing a scalar, and a value the type cannot read is
        // already a refusal — either way the generation does not survive to be emitted.
        _ => value_const(value),
    }
}

/// Whether the type this emits has items of its own, which is what makes an item-wise check right.
///
/// Asked of the type that is *emitted*, not of the one the spec wrote: `simplified` collapses a union
/// to its first member, so a `list<string>|string` looked like a list — while what is emitted for any
/// union is `Ty::Any`, which compares a value whole and would refuse the very default this had just
/// accepted. `option<T>` is looked through for the same reason the runtime looks through it.
fn declares_items(declared: Option<&SpecConfigType>) -> bool {
    match declared {
        Some(SpecConfigType::List(_) | SpecConfigType::Set(_) | SpecConfigType::Map(..)) => true,
        Some(SpecConfigType::Option(inner)) => declares_items(Some(inner)),
        _ => false,
    }
}

/// The type a *scalar* of this setting is read as.
///
/// Defaults and choices are scalars, so a collection is asked about what is in it. Every base type is
/// `const`-constructible without a reference, which is what makes this possible at build time at all:
/// the composite `Ty`s borrow, and nothing here can hand out a `&'static Ty`.
fn scalar_ty(declared: Option<&SpecConfigType>) -> usage_config::Ty {
    fn of(ty: &SpecConfigType) -> usage_config::Ty {
        match ty {
            SpecConfigType::Base(base) => match base {
                Base::Bool => usage_config::Ty::Bool,
                Base::String => usage_config::Ty::String,
                Base::Int => usage_config::Ty::Int,
                Base::Uint => usage_config::Ty::Uint,
                Base::Float => usage_config::Ty::Float,
                Base::Path => usage_config::Ty::Path,
                Base::Url => usage_config::Ty::Url,
                Base::Duration => usage_config::Ty::Duration,
                Base::Object => usage_config::Ty::Object,
                Base::Custom(_) => usage_config::Ty::Any,
            },
            SpecConfigType::List(inner) | SpecConfigType::Set(inner) => of(inner),
            SpecConfigType::Map(_, value) => of(value),
            SpecConfigType::Option(inner) => of(inner),
            // A union coerces nothing, and neither does this.
            SpecConfigType::Union(_) => usage_config::Ty::Any,
        }
    }
    declared.map_or(usage_config::Ty::String, of)
}

/// A spec value as the runtime holds one, for the coercion above.
fn runtime_value(value: &SpecConfigValue) -> usage_config::Value {
    match value {
        SpecConfigValue::Bool(b) => usage_config::Value::Bool(*b),
        SpecConfigValue::Int(i) => usage_config::Value::Int(*i),
        SpecConfigValue::Float(f) => usage_config::Value::Float(*f),
        SpecConfigValue::String(s) => usage_config::Value::String(s.clone()),
    }
}

/// A spec value as a user would have written it, for a message and for the comparison that falls
/// back to one.
///
/// Through the *runtime's* renderer, which is the only way the two can agree about anything: written
/// here as well, they drifted the moment one of them learned that a whole-number float is `1.0` and
/// not `1` — and this side would then have accepted a default the generated registry refuses.
fn display(value: &SpecConfigValue) -> String {
    runtime_value(value).display()
}

fn value_const(value: &SpecConfigValue) -> String {
    match value {
        SpecConfigValue::Bool(b) => format!("::usage_config::Const::Bool({b})"),
        SpecConfigValue::Int(i) => format!("::usage_config::Const::Int({i})"),
        // `{:?}` rather than `{}`: `1.0` written as `1` is an integer literal, and a `f64` field
        // will not take one.
        SpecConfigValue::Float(f) => format!("::usage_config::Const::Float({f:?})"),
        SpecConfigValue::String(s) => format!("::usage_config::Const::Str({})", rust_str(s)),
    }
}

/// Both spellings of the environment, in precedence order.
///
/// `env=` is the singular form and `env` the child node; the spec keeps them in step, and the
/// higher-precedence one comes first.
fn environment(prop: &SpecConfigProp) -> Vec<String> {
    let mut envs: Vec<String> = Vec::new();
    if let Some(env) = prop.env.as_deref() {
        envs.push(env.to_string());
    }
    for env in &prop.envs {
        if !envs.iter().any(|seen| seen == env) {
            envs.push(env.clone());
        }
    }
    envs
}

const PARSERS: [(&str, &str); 4] = [
    ("list_by_comma", "ListByComma"),
    ("list_by_colon", "ListByColon"),
    ("list_by_os_path_separator", "ListByOsPathSeparator"),
    ("set_by_comma", "SetByComma"),
];

fn parser(name: &str) -> Option<&'static str> {
    PARSERS
        .iter()
        .find(|(spec, _)| *spec == name)
        .map(|(_, variant)| *variant)
}

/// The const name for each key, and a problem for any two that would collide.
fn identifiers(props: &[(&String, &SpecConfigProp)], problems: &mut Vec<String>) -> Vec<String> {
    let mut idents = Vec::with_capacity(props.len());
    let mut seen: BTreeMap<String, String> = BTreeMap::new();
    for (key, _) in props {
        let ident = ident_of(key);
        if let Some(other) = seen.get(&ident) {
            // `task.output` and `task_output` are two settings and one const. Generating both
            // would not compile, which is a good outcome reported badly: the message names the
            // pair rather than leaving the author to read generated code.
            problems.push(format!(
                "`{key}` and `{other}` both generate `prop::{ident}`: rename one of them"
            ));
        } else {
            seen.insert(ident.clone(), (*key).clone());
        }
        idents.push(ident);
    }
    idents
}

fn ident_of(key: &str) -> String {
    let mut out = String::with_capacity(key.len());
    for c in key.chars() {
        match c {
            'a'..='z' | 'A'..='Z' | '0'..='9' => out.extend(c.to_uppercase()),
            // A dot, a dash, anything else: one underscore, so `task.output` and `task-output`
            // read the same way a Rust const is written.
            _ => out.push('_'),
        }
    }
    // A const cannot start with a digit, and a key may.
    if out.starts_with(|c: char| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

/// Refuse a key that cannot become a name.
///
/// An empty key generated `pub const : PropId = …`, and an empty part of one (`task..output`)
/// generated a field with no name: both are code the *adopter's* crate fails to compile, in a file
/// they did not write and cannot fix.
fn check_keys(props: &[(&String, &SpecConfigProp)], problems: &mut Vec<String>) {
    for (key, _) in props {
        if key.is_empty() {
            problems.push("a setting with no name cannot be generated".to_string());
        } else if !nameable(key) {
            problems.push(format!(
                "`{key}` has a part with no name in it: every piece of a dotted key needs an \
                 ASCII letter or digit"
            ));
        }
    }
}

/// Whether every part of `key` can be an identifier.
///
/// A part needs an ASCII letter or digit in it, which is the alphabet the names are actually built
/// from: `ident_of` keeps those and turns everything else into an underscore. Asking the wider
/// question — is any character of it alphanumeric — accepted `é` and then generated `_` for it, so
/// the two disagreed about the same key. Rust would take `É` as an identifier, but what an arbitrary
/// letter uppercases to is not something to bet a generated name on.
///
/// Empty (`task..output`) a part generated a field with no name; made only of characters outside
/// that alphabet (`-`) it generated an *anonymous* const — legal Rust, and unreferenceable, so the
/// reader that names it does not compile — and a field called `_`, which is not legal at all.
pub(crate) fn nameable(key: &str) -> bool {
    !key.is_empty()
        && key
            .split('.')
            .all(|part| part.chars().any(|c| c.is_ascii_alphanumeric()))
}

/// Refuse a `renamed_to` that cannot be followed.
fn check_renames(props: &[(&String, &SpecConfigProp)], problems: &mut Vec<String>) {
    let by_key: BTreeMap<&str, &SpecConfigProp> = props
        .iter()
        .map(|(key, prop)| (key.as_str(), *prop))
        .collect();
    for (key, prop) in props {
        let Some(to) = prop.renamed_to.as_deref() else {
            continue;
        };
        if !by_key.contains_key(to) {
            problems.push(format!(
                "`{key}` is renamed to `{to}`, which is not a setting"
            ));
            continue;
        }
        // Walking the chain from here, bounded by how many settings there are. A cycle makes
        // every lookup of these keys answer `None` at run time — the setting becomes unreachable
        // rather than wrong, which is the hardest kind of bug to see.
        let mut seen = vec![key.as_str()];
        let mut current = to;
        for _ in 0..props.len() {
            if seen.contains(&current) {
                problems.push(format!(
                    "the renames of `{}` form a cycle: {} → {current}",
                    seen[0],
                    seen.join(" → ")
                ));
                break;
            }
            seen.push(current);
            match by_key.get(current).and_then(|p| p.renamed_to.as_deref()) {
                Some(next) => current = next,
                None => break,
            }
        }
    }
}

/// `text` as a Rust string literal.
pub(crate) fn rust_str(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for c in text.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            // A control character written raw is a literal a compiler accepts and a reader cannot
            // see. `\u{…}` is the same string, spelled.
            c if c.is_control() => {
                let _ = write!(out, "\\u{{{:x}}}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Help text as one line, for a doc comment on a generated const.
pub(crate) fn one_line(text: &str) -> String {
    text.replace(['\n', '\r'], " ")
}
