use crate::cli::Cli;
use miette::Result;

pub(crate) fn generate() -> Result<()> {
    // The declaration *is* the spec: the same tables that parsed the command line print it,
    // with no bridge and no second model in between. `effect` in particular is now declared
    // on each command rather than patched in here afterwards, since clap could not say it.
    println!("// @generated by usage-cli from its own parse tables");
    println!("{}", Cli::to_kdl().trim());
    println!("{}", include_str!("../assets/usage-extra.usage.kdl").trim());

    Ok(())
}

pub(crate) fn complete(shell: &str) -> Result<()> {
    match shell {
        "bash" => print!("{}", include_str!("../assets/completions/usage.bash")),
        "fish" => print!("{}", include_str!("../assets/completions/usage.fish")),
        "zsh" => print!("{}", include_str!("../assets/completions/_usage")),
        _ => {
            miette::bail!("unsupported shell: {}", shell);
        }
    };

    Ok(())
}
