name: autofix.ci
on:
  workflow_call:
  pull_request:
  push:
    branches: ["main"]
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.actor != 'renovate[bot]' && github.actor != 'mend[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          shared-key: test
          save-if: false
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - name: Install shells for completion integration tests
        run: sudo apt-get update && sudo apt-get install -y zsh fish
      - run: mise r autofix
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
