name: release-plz

permissions:
  pull-requests: write
  contents: write
  id-token: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-plz

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_CONFIG_FUND: false

concurrency:
  group: release-plz

jobs:
  release-plz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          persist-credentials: true
      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
        with:
          experimental: true
          cache: false
      - run: mise trust --all
      - uses: rust-lang/crates-io-auth-action@bbd81622f20ce9e2dd9622e3218b975523e45bbe # v1.0.4
        id: auth
      - run: mise run release-plz
        env:
          GITHUB_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
