name: test
on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
        with:
          shared-key: test
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3
      - run: mise r build
      - run: mise r test
      - run: mise r lint
      - name: check wasm build
        run: rustup target add wasm32-wasip1 && cargo build --target wasm32-wasip1 -p usage-cli
